### ISSUE TITLE
Implement CSW 3.0

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#149]
- [x] review specification
- [x] abstract codebase to deal with multiple versions
  - [x] get csw2 working first
- [x] implement request handling / new XML Schemas / validation
- [x] implement response handling
- [x] add tests to `tests/suites/csw3`
- [x] pass [OGC CITE CSW3 tests](https://github.com/opengeospatial/ets-cat30)
- [x] pass [OGC CITE CSW2 tests](https://github.com/opengeospatial/ets-csw202)
- [x] decide default version behaviour
- [x] update documentation
- [x] update http://demo.pycsw.org
- [x] update website

**Comment by kalxas** [comment]
We have just branched master to https://github.com/geopython/pycsw/tree/csw3

**Comment by tomkralidis** [comment]
old branch now at https://github.com/kalxas/pycsw/tree/csw3-old

**Comment by tomkralidis** [comment]
Current status:

- passed: 115
- skipped: 1
- failed: 8

**Comment by kalxas** [comment]
We are now passing all CITE tests for CSW3 :)

**Comment by kalxas** [comment]
CSW3 support is merged in master now.
