### ISSUE TITLE
Limit anytext_vector records to 1MB for FTS use

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#210]
Currently we use PostgreSQL FTS to index our anytext column. For this, this text column gets transformed to tsvector type, which has a 1MB limit.
So in cases that anytext record is very large, the import will fail and FTS will not work:

```
pycsw=# UPDATE records SET anytext_tsvector = to_tsvector('english', anytext);
ERROR:  string is too long for tsvector (4556950 bytes, max 1048575 bytes)
```

We need to figure a way to limit this column during xml import. Some options:
1. shrink spaces, clear out special characters etc
2. remove xml specific strings (already done)
3. just cut the imported string at 1 MB without
4. move to other indexing methods like SOLR

**Comment by pvgenuchten** [comment]
still problematic to me, cut of at 1mb is probably better 

https://stackoverflow.com/questions/30470151/postgresql-how-to-go-around-ts-vector-size-limitations


```
CREATE TRIGGER ftsupdate2
    AFTER INSERT OR UPDATE 
    ON public.records
    FOR EACH ROW
    EXECUTE FUNCTION public.tsv_trigger_fn();

CREATE OR REPLACE FUNCTION public.tsv_trigger_fn()
    RETURNS trigger
    LANGUAGE 'plpgsql'
AS $BODY$
begin
  new.anytext_tsvector := to_tsvector('english', left(new.anytext, 1*1024*1024));
  return new;
end
$BODY$;
```
