### ISSUE TITLE
Support DCAT

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#257]
Implement support for http://www.w3.org/TR/vocab-dcat/

**Comment by tomkralidis** [comment]
## Implementation Options

### Ingest
- add hook and parser (`_parse_dcat`) to `pycsw.core.metadata`

### Output
- implement core outputschema plugin
 - outputschema: `http://www.w3.org/ns/dcat#`
 - serializer in `pycsw.plugins.outputschemas`

- example DCAT: http://demo.ckan.org/dataset/newcastle-city-council-payments-over-500.xml

**Comment by kalxas** [comment]
ISO to GeoDCAT XSLT:
https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/iso-19139-to-dcat-ap/browse

**Comment by kalxas** [comment]
Currently CKAN uses https://github.com/RDFLib

**Comment by kalxas** [comment]
GeoDCAT-AP has reached v1.0
https://joinup.ec.europa.eu/catalogue/distribution/geodcat-ap-version-10

**Comment by andrea-perego** [comment]
> ISO to GeoDCAT XSLT:
> https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/iso-19139-to-dcat-ap/browse

The reference XSLT implementation of GeoDCAT-AP has been moved to:

https://github.com/SEMICeu/iso-19139-to-dcat-ap/

**Comment by kalxas** [comment]
There is XSLT support now in pycsw master #761 so the GeoDCAT-AP XSLT can be configured to work directly with pycsw.

**Comment by Kate-Lyndegaard** [comment]
Can anyone provide a configuration example or additional documentation on how the GeoDCAT-AP XSLT can be used directly with pycsw?

**Comment by tomkralidis** [comment]
A minimal approach would be to define a DCAT [output schema plugin](https://docs.pycsw.org/en/latest/outputschemas.html), followed by an [XSLT configuration](https://docs.pycsw.org/en/latest/xslt.html) to the DCAT XSLT.

**Comment by Kate-Lyndegaard** [comment]
Thank you, @tomkralidis. I will give that a try.

**Comment by pvgenuchten** [comment]
maybe relevant here is the work in pygeometa https://github.com/geopython/pygeometa/blob/master/pygeometa/schemas/dcat/__init__.py to introduce a minimal dcat output based on json-ld, and work of @ldesousa to extend this work based on rdflib https://github.com/ldesousa/pygeometa/tree/issue%23180
