### ISSUE TITLE
Code Provenance Review

### ISSUE THREAD

**Issue by jmckenna** [geopython/pycsw#275]
- must perform a code review as per http://www.osgeo.org/incubator/process/codereview.html
- generate a review document similar to https://github.com/geoserver/geoserver/wiki/GeoServer-Provenance-Review

**Comment by tomkralidis** [comment]
@jmckenna thanks for kicking this off.  @kalxas and I worked on this and I think we're mostly done.  The updates are in `issue-275` branch. Outstanding items:

* [ ] update sources of the NTUA ISO XMLs in tests/suites/apiso/data/*.xml . Document in tests/suites/apiso/data/README.txt (@kalxas)

Anything else?

**Comment by kalxas** [comment]
I have submitted an e-mail to the pycsw-devel mailing list asking for more eyes to see the code.

**Comment by tomkralidis** [comment]
Should we close this one?

**Comment by kalxas** [comment]
The OGC issue is still valid, but yes we can close this one.
