### ISSUE TITLE
OGC Compliance Renewal for 1.10

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#296]

**Comment by kalxas** [comment]
Given all the work being done towards pycsw 2.0, I propose we submit 2.0 for OGC compliance renewal

**Comment by tomkralidis** [comment]
@kalxas status update?  Docs/website updated.  I believe the outstanding issue was to update the date on http://www.opengeospatial.org/resource/products/details/?pid=1325 ?

**Comment by kalxas** [comment]
Yes this is the only thing left, I will check again.
