### ISSUE TITLE
Code includes W3C schemas

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#307]
Linked with #275

**Comment by tomkralidis** [comment]
https://github.com/geopython/pycsw/tree/master/pycsw/schemas/w3c

**Comment by kalxas** [comment]
It seems from the OSGeo standards mailing list discussion that W3C schemas are ok to include in our source code:
http://lists.osgeo.org/pipermail/standards/2015-February/000840.html
http://lists.osgeo.org/pipermail/standards/2015-February/000842.html
