### ISSUE TITLE
update contributor and license agreements

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#312]
cc @jmckenna

## Overview
As part of OSGeo incubation, our Graduation Checklist (https://github.com/geopython/pycsw/wiki/Project-Graduation-Checklist) requires the project to firm up contribution agreements.

This applies to the pycsw software code files.

This is outlined in https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing.  Template for completing the agreement (per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing-agreement-template).

## Template

```Hi all, I'd like to contribute <feature X|bugfix Y|docs|code|something else> to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.```

Committers and contributors can either agree either via the pycsw-devel mailing list, or here in this ticket.

All committers and contributors are listed at https://github.com/geopython/pycsw/graphs/contributors

### Committers
- [x] @tomkralidis
- [x] @kalxas
- [x] @ahinz 

### Contributors
- [x] @gsaaportal (i.e. @DanRamage)
- [x] @milokmet
- [x] @simod 
- [x] @ingenieroariel 
- [x] @amercader 
- [x] @drwelby 
- [x] @kindly 
- [x] @sarametz 
- [x] @AxxL

**Comment by tomkralidis** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

Tom Kralidis

**Comment by kalxas** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

Angelos Tzotsos

**Comment by milokmet** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

Milo Kmet

**Comment by simod** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my
contributions to pycsw will be compatible with the pycsw license guidelines
at the time of contribution.

Simone Dalmasso

2015-01-30 19:27 GMT+01:00 Miloslav Kmet <notifications@github.com>:

> Hi all, I'd like to contribute code to pycsw. I confirm that my
> contributions to pycsw will be compatible with the pycsw license guidelines
> at the time of contribution.
>
> Milo Kmet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/pycsw/issues/312#issuecomment-72246609>.
>



-- 
Simone

**Comment by DanRamage** [comment]
Sorry about the gsaaportal confusion. I simply cannot get it to use my
DanRamage account for some reason.

**Comment by sarametz** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

Sara Metz

**Comment by amercader** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

Adrià Mercader

**Comment by ingenieroariel** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

**Comment by kalxas** [comment]
@DanRamage I think either your account or gsaaportal is fine, as long as it is documented here.
Thanks!

**Comment by AxxL** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

-Axel

**Comment by drwelby** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

**Comment by DanRamage** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

**Comment by ocefpaf** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

-Filipe Fernandes

**Comment by kindly** [comment]
Hi all, I'd like to contribute code to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.

-David Raznick

**Comment by kalxas** [comment]
Thank you all, the list is now complete.

**Comment by kalxas** [comment]
@tomkralidis should we close this issue or leave open for future contributors?

**Comment by tomkralidis** [comment]
@kalxas let's close? Future contribution agreements can be dealt with on a case by case basis, via pull requests, etc.
