### ISSUE TITLE
OGC Filters in KVP requests don't work

### ISSUE THREAD

**Issue by rouault** [geopython/pycsw#318]
The following request on a pycsw 1.10.1 server
http://data.linz.govt.nz/feeds/csw?SERVICE=CSW&REQUEST=GetRecords&version=2.0.2&elementsetname=full&resulttype=results&typenames=csw:Record&CONSTRAINTLANGUAGE=FILTER&constraint=%3Cogc:Filter%20xmlns:ogc=%22http://http://www.opengis.net/ogc%22%20xmlns:dc=%22http://purl.org/dc/elements/1.1/%22%3E%3Cogc:PropertyIsEqualTo%3E%3Cogc:PropertyName%3Edc:type%3C/ogc:PropertyName%3E%3Cogc:Literal%3Edataset%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E

emits the following exception :
```
<!-- pycsw 1.10.1 --><ows:ExceptionReport language="en-GB" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd"><ows:Exception exceptionCode="InvalidParameterValue" locator="constraint"><ows:ExceptionText>Invalid Filter query: Exception: document not valid.
Error: line 1: Couldn't find end of Start Tag Filter line 1.</ows:ExceptionText></ows:Exception></ows:ExceptionReport>
```

I've tried different variations around that request, and all fail. On the contrary, the same request sent as XML POST works.

**Comment by tomkralidis** [comment]
@rouault a couple of changes to your URL above (remove extra `http://`, `s/=/%3D/g` in `constraint` parameter) and it works for me:

http://data.linz.govt.nz/feeds/csw?SERVICE=CSW&REQUEST=GetRecords&version=2.0.2&elementsetname=full&resulttype=results&typenames=csw:Record&CONSTRAINTLANGUAGE=FILTER&constraint=%3Cogc:Filter%20xmlns:ogc%3D%22http://www.opengis.net/ogc%22%20xmlns:dc%3D%22http://purl.org/dc/elements/1.1/%22%3E%3Cogc:PropertyIsEqualTo%3E%3Cogc:PropertyName%3Edc:type%3C/ogc:PropertyName%3E%3Cogc:Literal%3Edataset%3C/ogc:Literal%3E%3C/ogc:PropertyIsEqualTo%3E%3C/ogc:Filter%3E

If this makes sense, we can add a test to the codebase for good measure.

**Comment by rouault** [comment]
Ah the error was the =  since I manually composed the URL in Firefox and it didn't realize that this equal sign had to be escaped... Sorry for spoiling your time on that.
If you've already KVP filters in your tests, no need for a duplicate.
Thanks!

**Comment by tomkralidis** [comment]
Added test for good measure in master, 1.10, and csw3 branches.  Thanks for the report @rouault!
