### ISSUE TITLE
OAIPMH implementation uses metadata date rather than insert date to select records

### ISSUE THREAD

**Issue by kevinpdavies** [geopython/pycsw#338]
A from (and/or until) attribute is passed in an OAIPMH ListRecords request when reharvesting a geonode with the intention of receiving new or modified records since the last harvest. For example:

    http://localhost/catalogue/csw?mode=oaipmh&verb=ListRecords&metadataPrefix=oai_dc&from=2015-06-02T00:00:00Z

geonode/pycsw uses the metadata date of the record (regardless of date type) to test whether it is greater than or equal to the requested **from** date.

However, the metadata date does not necessarily correspond to the date the record was added to geonode. For example, I have an aerial photograph that was published in 1941. If I put the metadata date type as 'published' and date as '1941-01-01T00:00:00Z', then this new record is not returned in a reharvest using the above URL.

I made the fix described below to get this working, but it is not ideal.

In **pycsw/oaipmy.ph** about line 150 I changed the query to use **dct:modified** rather than **dc:date** (I also had to add the timestamp decorator to get this working):

    LOGGER.info('Scanning temporal parameters')
    if 'from' in kvp:
        start = 'dct:modified >= \'%s\'::timestamp' % kvp['from']
    if 'until' in kvp:
        end = 'dct:modified <= \'%s\'::timestamp' % kvp['until']

**dct:Modified** is mapped to **pycsw:Modified**, which in turn is mapped to db column **date_modified** in pycsw/config.py which doesn't appear to exist. 

I changed **pycsw/config.py** (and geonode/catalogue/backends/**pycsw_local_mappings.py**) to map **pycsw:Modified** to the **csw_insert_date** db column. 

So this fix works OK - new records added to Geonode that may have an old publication date are included in a reharvest. However, if an existing geonode record is changed, this fix won't include these records.

Should there be a new **csw_modified_date** column in the db? I think I am getting way out of my depth so I am not confident about creating a pull request. but I hope my explorations may be useful.

**Comment by tomkralidis** [comment]
@kevinpdavies thanks for the in depth analysis / report.  This is addressed in https://github.com/GeoNode/geonode/issues/2187#issuecomment-111533768 and needs to be fixed in GeoNode proper.  I'll apply a patch shortly in GeoNode.

**Comment by tomkralidis** [comment]
@kevinpdavies FYI this fix has been applied to GeoNode master branch: https://github.com/GeoNode/geonode/issues/2187#issuecomment-112383250.  Does this work for you?
