### ISSUE TITLE
csw3.py conflicts with ebrim profile with default settings.

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#355]
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210] Traceback (most recent call last):
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]   File "/osgeo/demo.pycsw.org/pycsw/csw.wsgi", line 99, in application
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     status, contents = csw.dispatch_wsgi()
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]   File "/osgeo/demo.pycsw.org/src/pycsw/pycsw/server.py", line 293, in dispatch_wsgi
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     return self.dispatch()
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]   File "/osgeo/demo.pycsw.org/src/pycsw/pycsw/server.py", line 572, in dispatch
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     self.response = self.iface.getcapabilities()
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     return self.dispatch()
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]   File "/osgeo/demo.pycsw.org/src/pycsw/pycsw/server.py", line 572, in dispatch
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     self.response = self.iface.getcapabilities()
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]   File "/osgeo/demo.pycsw.org/src/pycsw/pycsw/ogc/csw/csw3.py", line 181, in getcapabilities
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210]     prof_val = self.parent.profiles['loaded'][prof].namespaces[prof_name]
[Thu Jul 02 12:19:26 2015] [error] [client 176.58.229.210] KeyError: 'ebrim'

**Comment by tomkralidis** [comment]
For some reason ebrim setting causes error when in CSW 3. Works fine for CSW 2.
