### ISSUE TITLE
server.dispatch() does not normalize KVP parameter names

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#362]
The `pycsw.server.Csw.dispatch` method does not normalize the names of KVP parameters. Instead it relies on the `dispatch_cgi` (line 229) and `dispatch_wsgi` (283) methods to do this. It would be cleaner to do this inside the `dispatch` method which is the next step in the request processing pipeline. 

Advantages:

* DRYier - We eliminate duplicate code
* It is easier to extend pycsw by calling server.dispatch

An example:

My current use case is integrating PyCSW with django. Inside my django view I instantiate the csw server and initialize it with the appropriate settings. Now I want to use the `server.dispatch` method, but I must remember to pre_process KVP param names to lower case.

This seems like an easy fix and I can supply a Pull Request with the modification in the near future

**Comment by tomkralidis** [comment]
@ricardogsilva this makes sense.  It would be great if this can be done in one place for both CGI/WSGI code paths.  Looking forward to a pull request.
