### ISSUE TITLE
tests do not clean up the environment after execution

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#367]
There seem to be two issues with running pycsw's test suites using paver:

```bash
paver test
```

1. The test runner starts up a local pycsw instance running on port 8000. However, it does not stop it when the tests finish.

2. The sqlite3 database at `tests/suites/cite/data/records.db` is modified by the tests and is not restored to its original state afterwards. This causes git to want to include it in commits.

**Comment by tomkralidis** [comment]
@ricardogsilva thanks for the report.  Comments:

- perhaps adding `call_task('stop') at the end of `paver test`?
- iirc, I think this is **not** cleaned up at the end of the test so devs can inspect the database after if required. We include the cite SQLite3 DB by default to give users something default as a bootstrap and for CITE reference implementation.  I do agree it is annoying and cumbersome to have git want to include it and is error prone for `git commit -am` type things.  Some options on how to deal with this:

1. cleanup/reset the DB after testing with `call_task('reset')`
1. rename the default cite DB to `tests/suites/cite/data/records.db` to `tests/suites/cite/data/cite.db` and this never clashes
1. others?

**Comment by kalxas** [comment]
git commit -am is not very wise ;)

**Comment by tomkralidis** [comment]
@ricardogsilva fixed with option 2 via #370 let me know if this works for you?

**Comment by ricardogsilva** [comment]
Hi @kralidis

I am currently on holidays until the second week of September. I'll get back to this then ;)

**Comment by ricardogsilva** [comment]
Hi Tom
I'll test this out tonight (or tomorrow) and report back, or close. Thanks!

**Comment by tomkralidis** [comment]
@ricardogsilva should we close this?

**Comment by ricardogsilva** [comment]
Yes, this is fixed now. Thanks @tomkralidis
