### ISSUE TITLE
pycsw fails with geolinks>=0.2.0

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pycsw#378]
pycsw==1.10.2 works with geolinks==0.0.1 but fails with the recent geolinks version:

     File "/home/pingu/.conda/envs/birdhouse/etc/pycsw/cswapp.py", line 61, in <module>
    from pycsw import server
    File "/home/pingu/.conda/envs/birdhouse/lib/python2.7/site-packages/pycsw/server.py", line 42, in <module>
    from pycsw import config, fes, log, metadata, util, sru, oaipmh, opensearch
    File "/home/pingu/.conda/envs/birdhouse/lib/python2.7/site-packages/pycsw/metadata.py", line 37, in <module>
    from geolinks.links import sniff_link
    ImportError: No module named links

**Comment by tomkralidis** [comment]
cc @kalxas 
@cehbrecht 1.10.2 is [tied](https://github.com/geopython/pycsw/blob/1.10/requirements.txt#L1) to geolinks 0.0.1.  master branch is [tied](https://github.com/geopython/pycsw/blob/master/requirements.txt#L1) to 0.2.0.

**Comment by tomkralidis** [comment]
@cehbrecht are you tied to geolinks 0.2.0 per se?  Can you peg to geolinks 0.0.1 for now?

**Comment by cehbrecht** [comment]
i pinned geolinks now to 0.0.1. no problem :) just noticed that pycsw was not starting ... got an update of geolinks from a different conda channel (ioos).

**Comment by ocefpaf** [comment]
@cehbrecht This is an issue I am trying to fix at the conda level.  Instead on pinning software versions here and there wouldn't it be better if we could use a preference order for our channels?

In your case you would just "downgrade" the ioos channel and only software that does not exist in your repo would come from the ioos channel.
