### ISSUE TITLE
Tidy up XML parsing code

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#380]
We should unify all the different `etree.XMLParser` objects that get created throughout the code into something more manageable because the current approach makes it hard to edit the parser options. Perhaps implementing a custom Parser that automatically sets up the arguments needed for safe XML parsing and use that one instead of the default?

One other thing that would be nice would be to try and have the various parts of the code that do the parsing closer to one another

**Comment by tomkralidis** [comment]
@ricardogsilva agreed.

## Observations

- `grep -R "etree.fromstring"` and `grep -R "etree.parse"` indicate all places in the codebase where we need to pass our custom `parser` argument
- [`lxml.etree.XMLParser`](http://lxml.de/api/lxml.etree.XMLParser-class.html) can be initiated with a `schema` argument which signifies a validating parser.  The default is a non-validating parser.  AFAICT it is **not** possible to update a `lxml.etree.XMLParser` object with a schema after it is initialized
- we want to ensure our custom parser is always set/init with `resolve_entities=False`
- sometimes we need to set a validating parser, sometimes we don't
- we validate XML **only** when (`grep -R XMLParser | grep schema)`:
 - parsing XML POST requests
 - parsing Filter XML passed via GET request via the `GetRecords` `constraint` parameter
- all other XML parsing is non-validating

## Option 1

Add `pycsw.util.get_parser`:

```python
    def gen_parser(self, schema=None):
        """return lxml.etree.XMLParser object"""

        return etree.XMLParser(schema=schema, resolve_entities=False)
```
Then calling works like:

```python
schema = 'my/xml/schema_file.xsd'
parser = pycsw.util.get_parser('my/xml/schema_file.xsd')  # validating
parser = pycsw.util.get_parser()  # non-validating:
etree.fromstring(my_string, parser)
```

## Option 2

Add `pycsw.core.config.StaticContext.parser` as a single living non-validating parser on init and always use that except for the (2) validating use cases.  We would need to make sure `pycsw.core.config.StaticContext` is available everywhere we need it

Comments/other ideas?

**Comment by tomkralidis** [comment]
@ricardogsilva PR #381 submitted based on option 2 for review/comment.

**Comment by tomkralidis** [comment]
Merged to master and backported to `1.10`, `1.8` and `py3k` branches.

**Comment by kalxas** [comment]
I think this issue should be closed now

**Comment by tomkralidis** [comment]
@ricardogsilva can you verify and if this works for you, close?

**Comment by ricardogsilva** [comment]
OK, I'll test it tonight and close then

**Comment by ricardogsilva** [comment]
It seems fine, ran the test suites and some extra files. Closing this down.
