### ISSUE TITLE
Documentation  - Update Deploy in 4 minutes

### ISSUE THREAD

**Issue by bunnis** [geopython/pycsw#399]
On a ubuntu 14.04, clean install, copy pasting the 'deploy ion 4 minutes' commands doesn't work. Beside the obvious apt-get issued by the shell, you still need some more packages. I'm listing all of them:

sudo apt-get install python-virtualenv git
sudo apt-get install python-dev libxml2-dev libxslt-dev
sudo apt-get install zlib1g-dev postgresql postgresql-server-dev-9.3 libpq-dev
sudo apt-get install libgeos-dev

**Comment by kalxas** [comment]
@bunnis postgresql packages are not needed for the minimum setup.

**Comment by tomkralidis** [comment]
We should probably, update the `requirements-standalone.txt` logic given it requires `psycopg2`.  Perhaps another `requirements-pg.txt` file?

**Comment by bunnis** [comment]
the libpq-dev package is at least needed

**Comment by tomkralidis** [comment]
@bunnis can you comment out/remove `psycopg2` from the `requirements-standalone.txt` file and report back/confirm on what's required based on that?  I'll update the codebase and docs appropriately thereafter.

**Comment by bunnis** [comment]
sudo apt-get install python-virtualenv git python-dev libxml2-dev libxslt-dev zlib1g-dev libpq-dev libgeos-dev
->follow the steps on deploy in 4 minutes (and removed psycopg2)


after curl http://localhost:8000/?service=CSW&version=2.0.2&request=GetCapabilities
I get this error. Let me know if you want more tests performed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "./pycsw/wsgi.py", line 101, in application
    status, contents = csw.dispatch_wsgi()
  File "/home/bunny/pycsw/pycsw/pycsw/server.py", line 266, in dispatch_wsgi
    return self.dispatch()
  File "/home/bunny/pycsw/pycsw/pycsw/server.py", line 564, in dispatch
    self.response = self.iface.getcapabilities()
  File "/home/bunny/pycsw/pycsw/pycsw/ogc/csw/csw2.py", line 313, in getcapabilities
    for qbl in self.parent.repository.queryables.keys():
AttributeError: 'Csw' object has no attribute 'repository'
100.100.2.91 - - [16/Feb/2016 10:19:54] "GET /?service=CSW&version=2.0.2&request=GetCapabilities HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "./pycsw/wsgi.py", line 101, in application
    status, contents = csw.dispatch_wsgi()
  File "/home/bunny/pycsw/pycsw/pycsw/server.py", line 266, in dispatch_wsgi
    return self.dispatch()
  File "/home/bunny/pycsw/pycsw/pycsw/server.py", line 564, in dispatch
    self.response = self.iface.getcapabilities()
  File "/home/bunny/pycsw/pycsw/pycsw/ogc/csw/csw3.py", line 343, in getcapabilities
    for qbl in self.parent.repository.queryables.keys():
AttributeError: 'Csw' object has no attribute 'repository'
100.100.2.91 - - [16/Feb/2016 10:19:54] "GET /favicon.ico HTTP/1.1" 500 59

**Comment by bunnis** [comment]
sudo apt-get install python-virtualenv git python-dev libxml2-dev libxslt-dev zlib1g-dev libpq-dev libgeos-dev (removed postgres stuff, except lipq-dev)
->follow the steps on deploy in 4 minutes (and removed psycopg2)

after curl http://localhost:8000/?service=CSW&version=2.0.2&request=GetCapabilities everything is ok

**Comment by tomkralidis** [comment]
@bunnis if you remove libpq-dev what package complains?  The 4 minute install is based on SQLite3.

**Comment by bunnis** [comment]
Everything seems ok by removing the libpq-dev package. The first time i did it i had some errors during the pip install requirements phase. Maybe something to do with psycopg2?

**Comment by tomkralidis** [comment]
@bunnis ok.  So I will create a `requirements-pg.txt` and moving psycopg2 there.  Then `requirements-standalone.txt` can run without issue for the 4 minute install.

**Comment by tomkralidis** [comment]
Thanks @bunnis for reporting!

**Comment by bunnis** [comment]
No Problem :D I have a new one for you, check #402
