### ISSUE TITLE
Opensearch Mode Error

### ISSUE THREAD

**Issue by bunnis** [geopython/pycsw#400]
Trying to issue a query with opensearch results in an internal error.
Query, as per http://docs.pycsw.org/en/latest/opensearch.html : 
http://100.100.0.201:8000/?mode=opensearch&?service=CSW&version=2.0.2&request=GetCapabilities

Server Response:
A server error occurred.  Please contact the administrator.

log at http://pastebin.com/VuHW0UuR

**Comment by tomkralidis** [comment]
@bunnis your OpenSearch request is malformed and should, instead, be like:

http://100.100.0.201:8000/?mode=opensearch&service=CSW&version=2.0.2&request=GetCapabilities

Having said this I have applied fixes to [master](https://github.com/geopython/pycsw/commit/cc83a7b6a0768f11aebe0bcffcc95e55e7f5ba8a) and [1.10](https://github.com/geopython/pycsw/commit/348ff94f2fbe365d3744764a007ffac942b44108) branch to provide a more graceful error.

Let us know if this works for you.

**Comment by bunnis** [comment]
Hi Tom
After further digging I found out this only happens on version 1.8.0 On 1.10.3 it works fine, my bad for not checking which version I was using. BTW, my request was ok, I did a copy paste error onto this issue. Thanks for updating the error message..

**Comment by bunnis** [comment]
In case you want to fix this in 1.8 I traced the error onto opensearch.py, node is used before being declared.

**Comment by tomkralidis** [comment]
thanks @bunnis pull requests for 1.8 branch are welcome, although we don't have release plans per se unless there is a driving demand/requirement.
