### ISSUE TITLE
Opensearch Mode Can't browse Index

### ISSUE THREAD

**Issue by bunnis** [geopython/pycsw#402]
I'm using pycsw 1.10.3 with Ckan 2.5.1. When I get the opensearch URL tehre is no mention to startIndex or StartPage in the template URL. Trying to manually add &searchIndex or &startPage doesn't yield any results. Is this intended or I'm just doing it wrong? Didn't find anything in the documentation and there are no test suites for opensearch from where I can check this.

description resutl from http://100.100.0.200/csw?mode=opensearch&service=CSW&version=2.0.2&request=GetCapabilities

```
<!--  pycsw 1.10.3  -->
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
<ShortName>pycsw Geospatial Catalogue</ShortName>
<LongName>pycsw Geospatial Catalogue</LongName>
<Description>
pycsw is an OGC CSW server implementation written in Python
</Description>
<Tags>catalogue discovery metadata</Tags>
<Url type="application/atom+xml" method="get" template="http://100.100.0.200/csw?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q={searchTerms?}&bbox={geo:box?}&time={time:start?}/{time:end?}"/>
<Image type="image/vnd.microsoft.icon" width="16" height="16">http://pycsw.org/img/favicon.ico</Image>
<Developer>Lastname, Firstname</Developer>
<Contact>Email Address</Contact>
<Attribution>Organization Name</Attribution>
</OpenSearchDescription>
```

Standard query result (notice the startIndex)
```
<!--  pycsw 1.10.3  -->
<atom:feed xmlns:os="http://a9.com/-/spec/opensearch/1.1/" xmlns:time="http://a9.com/-/opensearch/extensions/time/1.0/" xmlns:geo="http://a9.com/-/opensearch/extensions/geo/1.0/" xmlns:atom="http://www.w3.org/2005/Atom">
<atom:id>http://100.100.0.200/csw</atom:id>
<atom:title>pycsw Geospatial Catalogue</atom:title>
<os:totalResults>198</os:totalResults>
 <os:startIndex>1</os:startIndex>
<os:itemsPerPage>10</os:itemsPerPage>
<atom:entry xmlns:georss="http://www.georss.org/georss" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" xsi:schemaLocation="http://www.w3.org/2005/Atom http://www.kbcafe.com/rss/atom.xsd.xml">
<atom:category>Orthoimagery</atom:category>
<atom:id>8ec200fe-999d-48c2-9eb0-cbfe37aa9747</atom:id>
<atom:link href="None" title="None" type="None"/>
<atom:link href="http://100.100.0.200/csw?service=CSW&version=2.0.2&request=GetRepositoryItem&id=8ec200fe-999d-48c2-9eb0-cbfe37aa9747"/>
<atom:summary>ESA Sentinel Product Metadata</atom:summary>
<atom:title>
S1A_IW_RAW__0SSV_20160215T205942_20160215T210014_009962_00EA22_7A48.MANIFEST.SAFE
</atom:title>
<atom:updated>2016-02-15</atom:updated>
<georss:where>
<gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:6.11:4326">
<gml:exterior>
<gml:LinearRing>
<gml:posList>
144.93 65.0 139.07 65.0 139.07 62.69 144.93 62.69 144.93 65.0
</gml:posList>
</gml:LinearRing>
</gml:exterior>
</gml:Polygon>
</georss:where>
</atom:entry>
....
...
</atom:feed>
```

**Comment by tomkralidis** [comment]
@bunnis thanks for reporting this.  The CSW standard supports the `startPosition` and `maxRecords` parameters as part of the `GetRecords` operation.  Having said this, I think we simply need to expose `startIndex` and `count`parameters in the OpenSearch Description document.  Here's an example XML snippet with the aforementioned fix:

```xml
<Url type="application/atom+xml" method="get" template="http://100.100.0.200/csw?mode=opensearch&service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q={searchTerms?}&bbox={geo:box?}&time={time:start?}/{time:end?}&startposition={startIndex?}&maxrecords={count?}"/>
```
If this makes sense, I'll patch shortly.

**Comment by bunnis** [comment]
makes perfect sense!

**Comment by bunnis** [comment]
On another note, bout the time:start/time:end, should the / be replaced by two different times, like shown in this document? http://www.opensearch.org/Specifications/OpenSearch/Extensions/Time/1.0/Draft_1

&dtstart={time:start?}&dtend={time:end?}

I believe this is a draft for opensearch version 1.0, but the way time is done in pycsw doesn't seem to comply. Correct me if I'm wrong!

**Comment by bunnis** [comment]
An example descriptor link
` http://example.com/?q={searchTerms}&pw={startPage?}&dtstart={time:start}&dtend={time:end}&format=rss`
An example query:
`http://example.com/?q=news&dtstart=2007-02-12T04:30:02Z&dtend=2007-03-11T02:28:00Z&format=rss`

supported format 
 ```
YYYY-MM-DDTHH:mm:ssZ
 1996-12-19T16:39:57-08:00
```

**Comment by tomkralidis** [comment]
@bunnis fixed in master and 1.10 branch.

**Comment by tomkralidis** [comment]
cc @kalxas 

@bunnis pycsw implements the OGC OpenSearch Geo/Time Extensions standard.  You may want to bring this up on the pycsw mailing list for discussion.

Closing this issue proper.  Thanks again!

**Comment by bunnis** [comment]
Will do! Thanks
