### ISSUE TITLE
reword boilerplate description text wording

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#425]
# Description
We need to update our boilerplate text for describing pycsw.
# Environment
NA
# Steps to Reproduce
NA
# Additional Information

Areas to update:

- [x] docs
- [x] website
- [ ] packaging
- [x] Google+
- [x] Wikipedia
- [ ] other?

**Comment by tomkralidis** [comment]
cc @ricardogsilva 

Slight changes proposed.  The only change is to the 5th sentence which elaborates more on the various APIs we support:

```
pycsw is an OGC CSW server implementation written in Python.

pycsw fully implements the OpenGIS Catalogue Service Implementation Specification (Catalogue Service for the Web). Initial development started in 2010 (more formally announced in 2011). The project is certified OGC Compliant, and is an OGC Reference Implementation.

pycsw allows for the publishing and discovery of geospatial metadata. Existing repositories of geospatial metadata can also be exposed via numerous APIs (CSW 2/CSW 3, OpenSearch, OAI-PMH, SRU), providing a standards-based metadata and catalogue component of spatial data infrastructures.

pycsw is Open Source, released under an MIT license, and runs on all major platforms (Windows, Linux, Mac OS X).
```

**Comment by kalxas** [comment]
+1

**Comment by tomkralidis** [comment]
Thanks.

@kalxas: 

1. can you update the 'About Community' section on [Google+](https://plus.google.com/communities/104084873011085696113)?
2. who's the best person to ask to update this in Debian packaging?

**Comment by kalxas** [comment]
I will handle both

**Comment by kalxas** [comment]
Google+ done
Debian:
https://anonscm.debian.org/cgit/pkg-grass/pycsw.git/commit/?id=c059555b40af84ed8ca786aa8332385bfaa9ce37

**Comment by kalxas** [comment]
what else in packaging? Pypi?

**Comment by tomkralidis** [comment]
PyPI will get automagically updated when we publish the release.

**Comment by kalxas** [comment]
ok, then we are done.
