### ISSUE TITLE
Make tests more robust to small XML differences

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#427]
We are currently using a mix of `cmplib.cmp()` and `difflib.unified_diff()` for comparing test results with their expected values. This approach is flaky because XML files can have some differences in syntax but still be semantically equal, the main example being the order by which attributes are written in an XML element.

A nicer alternative to the current implementation seems to be the usage of [XML canonicalization](https://en.wikipedia.org/wiki/Canonical_XML), which is available in `lxml` by means of the `write_c14n()` method of an ElementTree object. There is a nice example of its application on this stackoverflow thread:

http://stackoverflow.com/a/30013395

**Comment by tomkralidis** [comment]
:+1: Makes sense.  This would also give a bit of a performance boost, given we now have many iterations wrapped in `sorted` just to ensure tests pass, so we can then remove these given c14n would be the default means of evaluation.

With [c14n](http://lxml.de/api.html#write-c14n-on-elementtree) as the default, it would help to keep the existing in the code, which could be triggered (if desired) with a `-p` (pedantic) flag.

@ricardogsilva thoughts?

**Comment by ricardogsilva** [comment]
@tomkralidis I'm preparing a PR for this and I'm facing some errors with lxml's c14n. The errors boil down to this:

```python
lxml.etree.C14NError: Relative namespace UR is invalid here : java
```

Looking into the XML file I am seeing xml namespace declarations like:

```xml
xmlns:tec="java:com.occamlab.te.TECore" 
xmlns:tems="java:com.occamlab.te.web.MonitorServlet"
```

As an example, please check `tests/suites/cite/post/f7d79701-f10b-4087-a33c-f62df0a04fd1.xml`

I guess lxml is complaining about the usage of a prefix (in this case java:) inside a namespace declaration. I don't really understand the purpose for these namespace declarations as they don't seem to be used in the rest of the XML documents.

I've looked through the [ets-csw202](https://github.com/opengeospatial/ets-csw202) CITE tests, made a search for these namespace declarations and they do not show up there. However, they are present in many (all?) POST tests of our CITE suite.

@tomkralidis do you have some insight on this? I'm stumped.

**Comment by tomkralidis** [comment]
@ricardogsilva FYI the files from `tests/suites/cite` (and the uuid-ish ones now in `tests/suites/csw30` are taken verbatim during a real session and saved locally for the purpose of pseudo-testing CITE as part of our CI (note we still manually test CITE as part of our release process).  If these (or any other test XML files) have namespaces which are not used, feel free to delete them from the XML.

Having said this, XML test files like `tests/expected/suites_sru_get_search_maxrecords.xml` have similar types of relative namespaces which *are* required and will cause issues with c14n serialization, so you will probably run into this there.  Not sure how to workaround those.
