### ISSUE TITLE
Move to py.test as a testing framework

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#428]
We are currently using a fairly involved testing framework that has been custom tailored for pycsw. It features lots of functional tests for many suites. However, personally I find it hard to work with it because:
- It is hard to pinpoint errors when executing the `run_tests.py` script because of all of the output that it generates
- The previous state of a test run can influence the outcome of a new run
- The setup and cleanup tasks are defined in the `pavement.py` file, while the tests themselves are located elsewhere
- There is a lot noise with new files being generated and deleted in the project's directory

I propose moving to [pytest](http://pytest.org/latest/) as a more standard testing framework. It seems like a good choice because:
- It seems to be the de facto standard for python testing nowadays
- It is easy to install and works across Python versions
- Has lots of cool plugins and can generate reports that integrate with other tools
- It is great for writing all kinds of tests, from unit tests to integration to functional (which is what most of our tests are)
- It does a lot of stuff automatically, like hiding the output of tests that pass

I'm willing to work on the code and make this happen, if there is interest in it.

**Comment by tomkralidis** [comment]
:+1: I'm supportive of this for 2.0.0.  Looking forward to it!

**Comment by tomkralidis** [comment]
@ricardogsilva I would suggest an [RFC](http://pycsw.org/development/rfc/) for this work ([example](https://github.com/geopython/pycsw.org/blob/gh-pages/development/rfc/rfc-6.md))

**Comment by ricardogsilva** [comment]
@tomkralidis OK, I'll look into creating the RFC in the coming days then.

**Comment by tomkralidis** [comment]
Sounds good @ricardogsilva.  Related issues which this work may end up helping or be helped by this work are #415 and #320.

**Comment by tomkralidis** [comment]
FYI the approved RFC is at: http://pycsw.org/development/rfc/rfc-8.html

@ricardogsilva any update on implementation?

**Comment by ricardogsilva** [comment]
Hi @tomkralidis 
I've become the father to a beutiful baby girl last month (drools) :)

As such I've had to put some of this work on hold for now - I hoped to be able to get it done before her birth, but I guess I was too optimistic. I'm expecting to come back to this by late September. You'll be hearing from me then! Cheers

**Comment by tomkralidis** [comment]
Sounds good @ricardogsilva -- congratulations!!!

**Comment by ricardogsilva** [comment]
FYI, I'm still working on this:

https://github.com/ricardogsilva/pycsw/tree/issue%23428

It is coming along nicely and I currently have all local tests already integrated into py.test and passing. There is still some work left to do but I hope to get it ready soon.

**Comment by ricardogsilva** [comment]
Closing this issue because the RFC has already been accepted and the PR has been merged to master
