### ISSUE TITLE
Support geolinks 0.2.0

### ISSUE THREAD

**Issue by sebastic** [geopython/pycsw#439]
As reported by @kalxas in [OSGeo-Live Trac #1705](https://trac.osgeo.org/osgeo/ticket/1705#comment:2):
> python-geolinks needs to be downgraded to 0.0.1 to be compatible with pycsw 1.x

python-geolinks won't be downgraded to 0.0.1 in Debian and Ubuntu which already have 0.2.0, so getting support for geolink 0.2.0 in PyCSW is needed.

Documenting the version requirements of dependencies would be nice to.

**Comment by kalxas** [comment]
geolinks 0.2.0 broke the API and works fine with pycsw master, which is going to be pycsw 2.x
pycsw 1.x branch is still using geolinks 0.0.1 as can be seen here:
https://github.com/geopython/pycsw/blob/1.10/requirements.txt#L1

I propose we backport support for geolinks 0.2 from master to 1.10 branch

**Comment by kalxas** [comment]
the latest stable release now supports geolinks 0.2.0
