### ISSUE TITLE
Sharing the results of a Static Code Analysis

### ISSUE THREAD

**Issue by JJediny** [geopython/pycsw#443]
# Description

Sharing the results of a Static Code Analysis from a security audit

`python setup.py build`
# Environment

Ubuntu 14.04 using python 2.7
- Bandit
- pylint
- flake
# Results

[SWAMP_bandit-pylint-flake_CAreview_pyCSW.csv.zip](https://github.com/geopython/pycsw/files/320787/SWAMP_bandit-pylint-flake_CAreview_pyCSW.csv.zip)

**Comment by JJediny** [comment]
Like it to be said that there were:
0 critical
0 High
0 Moderate
2 Low
{{ the rest }} unknown

**Comment by kalxas** [comment]
@JJediny Thank you for the feedback, it is much appreciated.
