### ISSUE TITLE
fix XML validation error

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#454]
# Description

As per #453, XML validation fails when using lxml >=3.6.3.
# Environment
- operating system: ubuntu trusty
- Python version: 2.7
- pycsw version: `master`
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 
# Steps to Reproduce

See #453 test results.
# Additional Information

The issue is rooted either in lxml or libxml2: https://mailman-mail5.webfaction.com/pipermail/lxml/2016-August/007757.html

**Comment by tomkralidis** [comment]
Turns out it's a libxml2 error in 2.9.4.  2.9.3 works.

**Comment by kalxas** [comment]
Lets keep this open for reference by external projects

**Comment by tomkralidis** [comment]
+1.  Associated [bug report, test case, and patch](https://bugzilla.gnome.org/show_bug.cgi?id=766834).

**Comment by tomkralidis** [comment]
@kalxas this is now resolved/fixed upstream. Wondering if these fixes have made it to packaging?

**Comment by kalxas** [comment]
I see that libxml2 released 2.9.7 few days ago.
@tomkralidis which is the upstream release that included that fix? The last one?

**Comment by kalxas** [comment]
https://github.com/GNOME/libxml2/blob/72182550926d31ad17357bd3ed69e49d7e69df02/doc/news.html#L258
so it was 2.9.4 that fixed this issue

**Comment by kalxas** [comment]
Debian 9.0: libxml2 2.9.4+dfsg1-2.2+deb9u1
Ubuntu Xenial: libxml2 2.9.3+dfsg1-1 
Ubuntu Bionic: libxml2 2.9.4+dfsg1-5ubuntu1
Redhat EL 7 / CentOS: libxml2 2.9.1-6.el7_2.3
openSUSE Leap 42.3: libxml2-2.9.4-12.1

Only RedHat/CentOS 7 and Debian 8.0 (old stable) have the old libxml version.

**Comment by tomkralidis** [comment]
@kalxas can we close?  Perhaps enough time has gone by where newer versions of libxml2 are now widespread.

**Comment by kalxas** [comment]
Debian 9.0: libxml2 2.9.4+dfsg1-2.2+deb9u2
Debian 10.0: libxml2 2.9.4+dfsg1-7+b3
Ubuntu Xenial: libxml2 2.9.3+dfsg1-1ubuntu0.6
Ubuntu Bionic: libxml2 2.9.4+dfsg1-6.1ubuntu1.2
RedHat EL 7/CentOS: libxml2 2.9.1-6.el7_2.3
RedHat EL 8: not known yet
openSUSE Leap 15.0: libxml2 2.9.7
openSUSE Leap 15.1: libxml2 2.9.7
