### ISSUE TITLE
Support of more resource types in harvesting (e.g. WMS 1.3.0)

### ISSUE THREAD

**Issue by klimeto** [geopython/pycsw#464]
# Description
Looking for support of more resource types in transaction harvesting operations. For example WMS 1.3.0, WFS 2.0, WCS 2.0 etc.

**Comment by tomkralidis** [comment]
@klimeto thanks for the report.  Our harvesting almost exclusively relies on underlying OWSLib support.  So the first place to look/implement is via OWSLib support.  Following this, a simple implementation / update in `pycsw.core.metadata` to cycle through the resource and set as a pycsw object (see `pycsw.core.metadata._parse_wms` as an example).

Having said this, I would suggest foreach standard/version enhancement that this be entered as an individual GitHub issue/ticket so we can implement and track accordingly.  Perhaps we can start with WMS 1.3.0 as a new ticket/example?

For those interested in implementing and submitting a GitHub Pull Request (preferred and welcome!), a great example can be the WMTS harvesting example in #422 by @jfdickens.

Note that for WMS 1.3.0, WFS 2.0, WCS 2.0, the core standards are already implemented in OWSLib and pycsw, so from a pycsw viewpoint this is simply a matter of doing version negotiation to call OWSLib with the correct version, and if not found/exception, then move on to the next/lower supported version.

**Comment by tomkralidis** [comment]
@klimeto FYI WMS 1.3.0 is now implemented in master branch.

For additional harvesting types, let's open/track individually.  Closing this ticket
