### ISSUE TITLE
support WFS 1.0.0 harvesting

### ISSUE THREAD

**Issue by klimeto** [geopython/pycsw#469]
# Description
Adds support for WMS 1.0.0 harvesting.
# Related Issues / Discussion
#468 
#464 
#467

**Comment by tomkralidis** [comment]
@klimeto thanks for the report.  CSW harvesting requires a `resourcetype` parameter which, for WFS, we use `http://www.opengis.net/wfs` which corresponds to the target namespace for WFS 1.0.0. This is the exact same namespace for WFS 1.1.0 (note that for WFS 2.0.0 the target namespace is `http://www.opengis.net/wfs/2.0`).

Having said this, a pycsw Harvest with `resourcetype=http://www.opengis.net/wfs` will try by default with a WFS 1.1.0 `GetCapabilities` request, given there is no other way to specify the WFS version in a CSW harvest request per se (for WFS 1.0.0/1.1.0, given they share the same namespace).

Do you have any example WFS instances that **only** work with WFS 1.0.0 (i.e. do not support WFS 1.1.0)?

**Comment by tomkralidis** [comment]
Implemented in master. For WFS 1.x pycsw will try 1.1.0 then 1.0.0 on 1.1.0 error.
