### ISSUE TITLE
Don't require a specific version of lxml

### ISSUE THREAD

**Issue by mohmad-null** [geopython/pycsw#477]
PyCSW requires a specific version of the lxml library. This is a significant problem for windows users because... well that library is an absolute pain to install (not that it looks to be any easier on linux based on the number of votes here - http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu?rq=1 ).

I have 3.6.4 installed, but the requirements for PyCSW 2.0.1 specify == 3.6.2. I'm struggling to find a pre-compiled version to use (as windows/pip doesn't seem to be able to create it itself - lots of errors).
Can you please change it back to >=, rather than ==.

**Comment by mohmad-null** [comment]
Same of Pyproj - it seems to have a bug that means it doesn't install on windows ( http://stackoverflow.com/questions/34427788/how-to-successfully-install-pyproj-and-geopandas ). 
I can get a pre-compiled current version that will install, but it's going to be newer than the version that PyCSW accepts.

**Comment by ocefpaf** [comment]
@mohmad-null you can try the `conda` and `conda-forge` binaries.

```shell
conda create -n PYCSW -c conda-forge python=3.5 pycsw 
```

They should download the proper [`lxml`](https://github.com/conda-forge/pycsw-feedstock/blob/master/recipe/meta.yaml#L22) version and the binaries for all the dependencies are available on Linux, Windows, and OS X.

**Comment by kalxas** [comment]
There have been reported some parsing issues with latest lxml and libxml2, so until these are resolved I would not touch the requirements yet.
