### ISSUE TITLE
Add Python 3 Trove classifiers

### ISSUE THREAD

**Issue by tveastman** [geopython/pycsw#480]
Can you please ensure that PyPI knows which versions of Python PyCSW supports?

Assuming PyCSW is supports the versions of Python specified in your .travis.yml file. It should be as simple as adding:

```
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3.4
```

Tools like `caniusepython3` will assume that PyCSW is not Python3 ready without these classifiers.

Cheers!

**Comment by kalxas** [comment]
Thanks for the feedback.
Indeed pycsw supports python 3, we just forgot to update the Pypi metadata, which is a bit ironic given that we are a metadata catalogue :)

**Comment by tomkralidis** [comment]
Applied to master and 2.0 branch.  Thanks @tveastman!
