### ISSUE TITLE
Remote tests failing

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#485]
# Description

While working on #428 I'm running into an issue where two tests of the `harvesting` suite are failing. The tests and a diff of expected vs result are:

1. `Harvest-zzz-post-GetRecords-filter-wfs-iso`

```
--- Harvest-zzz-post-GetRecords-filter-wfs-iso/expected.xml	2016-11-16 16:49:08.005763367 +0000
+++ Harvest-zzz-post-GetRecords-filter-wfs-iso/response.xml	2016-11-16 16:51:15.607320617 +0000
@@ -703,26 +703,6 @@
           <srv:containsOperations>
             <srv:SV_OperationMetadata>
               <srv:operationName>
-                <gco:CharacterString>DefaultMaxFeatures</gco:CharacterString>
-              </srv:operationName>
-              <srv:DCP>
-                <srv:DCPList codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#DCPList" codeListValue="HTTPGet">HTTPGet</srv:DCPList>
-              </srv:DCP>
-              <srv:DCP>
-                <srv:DCPList codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#DCPList" codeListValue="HTTPPost">HTTPPost</srv:DCPList>
-              </srv:DCP>
-              <srv:connectPoint>
-                <gmd:CI_OnlineResource>
-                  <gmd:linkage>
-                    <gmd:URL>http://maps.cera.govt.nz/arcgis/services/CERA/CERA_TechClasses_WGS84/MapServer/WFSServer</gmd:URL>
-                  </gmd:linkage>
-                </gmd:CI_OnlineResource>
-              </srv:connectPoint>
-            </srv:SV_OperationMetadata>
-          </srv:containsOperations>
-          <srv:containsOperations>
-            <srv:SV_OperationMetadata>
-              <srv:operationName>
                 <gco:CharacterString>ImplementsSimpleWFS</gco:CharacterString>
               </srv:operationName>
               <srv:DCP>

```

2. `Harvest-zzz-post-GetRecords-filter-wms-iso`

```
--- expected.xml	2016-11-16 17:05:23.287145828 +0000
+++ response.xml	2016-11-16 17:06:47.897533902 +0000
@@ -1103,7 +1103,7 @@
               </gmd:address>
               <gmd:onlineResource>
                 <gmd:linkage>
-                  <gmd:URL>http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?</gmd:URL>
+                  <gmd:URL>https://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?</gmd:URL>
                 </gmd:linkage>
               </gmd:onlineResource>
             </gmd:CI_Contact>

```

It seems like the remote servers have made some changes to the records being harvested. If so, perhaps we should update the expected files to reflect this. I am not sure of this assumption though.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
 - [x] git clone
 - [ ] DebianGIS/UbuntuGIS
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify):
- web server
 - [x] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

* Clone the latest pycsw master and install dev dependencies.
* Run the remote tests with

```
paver test -r
```

There should be two failing tests

# Additional Information

I am attaching the full results and responses here:

[failing_harvesting_tests.zip](https://github.com/geopython/pycsw/files/595370/failing_harvesting_tests.zip)

**Comment by tomkralidis** [comment]
@ricardogsilva agree.  This usually happens from time to time given the nature of testing remotes.  Feel free to update (in master) the expected result.

**Comment by ricardogsilva** [comment]
OK, I'll do that then.
