### ISSUE TITLE
adjust severity in logging statements 

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#498]
# Description
Review all logging statements to more properly use severity (e.g. errors should be level error, not debug).  This will reduce verbosity of logging relevant to the loglevel specified.
# Environment

- operating system: any
- Python version: all
- pycsw version: master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information
Thanks to @warmerdam for the valuable feedback.

**Comment by kalxas** [comment]
Thanks @warmerdam for the feedback!
