### ISSUE TITLE
update Python supported versions

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#502]
# Description

Retire 2.6 support and ensure 3.5 support on PyPI.

# Environment

- operating system: all
- Python version: 2.x/3.x
- pycsw version: master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information
discussion: https://gitter.im/geopython/pycsw?at=58bd73dd1465c46a56f2bd1c

https://pythonclock.org/

**Comment by ricardogsilva** [comment]
@tomkralidis I'll go ahead and also remove python2.6 from the `tox.ini` file. It is not related directly with packaging (more with testing) but I guess it is no longer needed. I've opened #513 to track this.

**Comment by tomkralidis** [comment]
+1 thanks @ricardogsilva
