### ISSUE TITLE
support Python 3 based packages

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#504]
# Description

Add Python 3 ecosystem support for pycsw packages / distribution.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [] git clone
  - [x] DebianGIS/UbuntuGIS
  - [x] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by kalxas** [comment]
https://packages.debian.org/sid/python3-pycsw
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-experimental/+sourcepub/9004353/+listing-archive-extra

**Comment by kalxas** [comment]
For the debian packaging do we want to switch to python3 as default?

**Comment by tomkralidis** [comment]
+1 it is time. How long will the old versions on trusty continue to be available?

**Comment by kalxas** [comment]
which ones, the UbuntuGIS or the upstream Ubuntu?

**Comment by tomkralidis** [comment]
UbuntuGIS

**Comment by kalxas** [comment]
I guess until 2020

**Comment by kalxas** [comment]
This has already happened in UbuntuGIS/Debian.
