### ISSUE TITLE
There is no way to get PYCSW_CONFIG from the os environment when using wsgi servers

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#508]
# Description

We ship the `pycsw.wsgi` module, which can be used to launch pycsw standalone by simply running

    python pycsw/wsgi

pycsw then tries to pick up the `PYCSW_CONFIG` variable from the [environment](https://github.com/geopython/pycsw/blob/master/pycsw/wsgi.py#L71) and failing that it will later try to get its configuration file from pycsw's home directory.

This works when running the provided `pycsw.wsgi` module standalone but it fails when using a wsgi http server, like [gunicorn](http://gunicorn.org/). When trying to run

    export PYCSW_CONFIG=/etc/pycsw/pycsw.cfg
    gunicorn --workers 2 --bind 0.0.0.0:8000 pycsw.wsgi

pycsw cannot find the `PYCSW_CONFIG` variable in the environment. 

There are two environments  here:

- The request's environment - This one gets set by the server implementing the WSGI spec and is related to the request being handled. It is provided as the `environ` argument to the `pycsw.wsgi:application` function by the wsgi server;
- The app's environment - This is inherited from the process where pycsw is started, and is accessible using `os.environ`;

Somehow there seems to be a divergent vision between python's `wsgiref.WSGIServer` and `gunicorn`:

- `WSGIServer` seems to merge both environments into the `env` argument of the `application` function;
- gunicorn keeps the two environments separated;

A possible fix for this is to simply try to read the value of `PYCSW_CONFIG` with `os.getenv` too, in addition to the current method.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [x] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): gunicorn

# Steps to Reproduce

In order to ease debugging, add the following two lines to `pycsw.wsgi`, on line 67

    print("PYCSW_CONFIG from env: {}".format(env.get("PYCSW_CONFIG")))
    print("PYCSW_CONFIG in os.environ: {}".format(os.getenv("PYCSW_CONFIG")))

Now launch pycsw using `pycsw.wsgi`

    $ export PYCSW_CONFIG=/etc/pycsw/pycsw.cfg
    $ python pycsw/wsgi.py
    Serving on port 8000...

And make a request to the server using another terminal

    $ wget localhost:8000

pycsw replies with:

    PYCSW_CONFIG from env: /etc/pycsw/pycsw.cfg
    PYCSW_CONFIG in os.environ: /etc/pycsw/pycsw.cfg

Now try the same thing using gunicorn. Start pycsw with:

    $ pip install gunicorn
    $ gunicorn --workers 2 --bind 0.0.0.0:8000 pycsw.wsgi

Using another terminal, make the same request (using wget). gunicorn replies with:

    PYCSW_CONFIG from env: None
    PYCSW_CONFIG in os.environ: /etc/pycsw/pycsw.cfg

# Additional Information

I'm willing to submit a PR with a fix for this

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva.  PR fix welcome.
