### ISSUE TITLE
Fix WMS harvest issue

### ISSUE THREAD

**Issue by minhd** [geopython/pycsw#514]
# Description
The creation of service record from a WMS server fail when setting the `pycsw:AnyText`. The error returns is
```
[ERROR] file=/opt/pycsw/pycsw/ogc/csw/csw2.py line=1304 module=csw2 function=harvest 'module' object has no attribute 'get_anytext'
```
Upon closer inspection, the line that causes the error calls `set(context, serviceobj, 'pycsw:AnyText', util.get_anytext(md.getServiceXML()))` of which `util.get_anytext` is undefined. 

A possible replacement of that would be
```
_set(
        context,
        serviceobj,
        'pycsw:AnyText',
        repository.get_anytext(md.getServiceXML())
    )
```

I have prepared a commit for it https://github.com/minhd/pycsw/commit/aa5d377ac8def09d64fd9bd5ab9259ac19af814a and can issue a PR anytime

# Environment

- operating system: alpine
- Python version: 2.7
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): Apache/mod_proxy docker

# Steps to Reproduce
Issue a harvest request with the following payload
```
<?xml version="1.0" encoding="UTF-8"?>
<Harvest xmlns="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:ows="http://www.opengis.net/ows" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-publication.xsd" service="CSW" version="2.0.2">
  <Source>http://dapds00.nci.org.au/thredds/wms/fx3/gbr1/gbr1_simple_2016-03-30.nc</Source>
  <ResourceType>http://www.opengis.net/wms</ResourceType>
  <ResourceFormat>application/xml</ResourceFormat>
</Harvest>

```

**Comment by ricardogsilva** [comment]
Hi @minhd 
Thanks for reporting this. This problem comes from a [recent refactoring](https://github.com/geopython/pycsw/pull/501) of the `pycsw.core.util` module.

A PR would be welcome, thanks in advance.

I'll also check to see if there might be other references to this function elsewhere in the code.

**Comment by tomkralidis** [comment]
@minhd thanks for the report. I echo @ricardogsilva's suggestion.  Looks like we also need to make a fix in https://github.com/geopython/pycsw/blob/master/pycsw/plugins/repository/odc/odc.py#L61. Thanks in advance!

**Comment by minhd** [comment]
I've issued a PR https://github.com/geopython/pycsw/pull/518
