### ISSUE TITLE
Add HTTP_X_FORWARDED_FOR to ipaddress testing for CSW-T operation

### ISSUE THREAD

**Issue by minhd** [geopython/pycsw#515]
# Description
When putting pycsw running behind a proxy server, forwarding IP will need to be used to check for permission against `allowed_ips`, currently only `REMOTE_ADDR` is used

I've prepared a commit for it at https://github.com/minhd/pycsw/commit/7e6d52b7ce8ced0e6a524b27ebd0be49cc88393a and can issue a PR anytime

# Environment

- operating system:
- Python version: 2.7
- pycsw version: 
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): mod_proxy to a docker container

# Steps to Reproduce
Run a docker container for pycsw in bridged networking mode, the `REMOTE_ADDR` will always be set to the docker machine ip address

**Comment by ricardogsilva** [comment]
Hi @minhd 
Seems like a sensible approach. Please submit the PR then. Thanks :)

**Comment by tomkralidis** [comment]
+1, thanks @minhd

**Comment by minhd** [comment]
:) PR submitted https://github.com/geopython/pycsw/pull/519

**Comment by ricardogsilva** [comment]
Merged #519

**Comment by kalxas** [comment]
Thanks @minhd
