### ISSUE TITLE
Store the version on a single location

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#516]
# Description

We're currently duplicating our version number on two different files:

- `VERSION.txt`
- `pycsw/__init__.py`

This is somewhat error prone, as one has to remember to keep these two in sync. Another issue is that in our `setup.py` file we are importing pycsw in order to extract the version number. This can become problematic under certain circumstances:

https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package/2073599#2073599

Following the advice on the linked stackoverflow answer, we can put the version in a single file, lets say `VERSION` and then use python's `pkgresources` to extract it at runtime. This means we get to store pycsw's version in a single location.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify):

**Comment by tomkralidis** [comment]
cc @kalxas 

@ricardogsilva good idea. Note when implemented/merge we should also update our Release Packaging steps (https://github.com/geopython/pycsw/wiki/Release-Packaging#step-3 and https://github.com/geopython/pycsw/wiki/Release-Packaging#step-10) accordingly.

**Comment by kalxas** [comment]
+1

**Comment by ricardogsilva** [comment]
I'll update the release docs too then

**Comment by tomkralidis** [comment]
Just hacked them :)
