### ISSUE TITLE
Running PYCSW without Environment causes configuration failure

### ISSUE THREAD

**Issue by minhd** [geopython/pycsw#528]
# Description
Using the 4 minute installation guide
```
        # Grab the pycsw source code:
        $ git clone https://github.com/geopython/pycsw.git && cd pycsw
        $ pip install -e . && pip install -r requirements-standalone.txt
        
        # Create and adjust a configuration file:
        $ cp default-sample.cfg default.cfg
        $ vi default.cfg
        # adjust paths in
        # - server.home
        # - repository.database
        # set server.url to http://localhost:8000/
        
        # Setup the database:
        $ pycsw-admin.py -c setup_db -f default.cfg
        
        # Load records by indicating a directory of XML files, use -r for recursive:
        $ pycsw-admin.py -c load_records -f default.cfg -p /path/to/xml/
        
        # Run the server:
        $ python ./pycsw/wsgi.py
        
        # See that it works!
        $ curl http://localhost:8000/?service=CSW&version=2.0.2&request=GetCapabilities
```

Results in an error
```
"GET /?service=CSW&version=2.0.2&request=GetCapabilities HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "./pycsw/wsgi.py", line 85, in application
    csw.config.get("server", "gzip_compresslevel"))
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'server'
```

I've traced back the changes to the commit f8e0c88171aac52d254c4ce3ba6a7b0b4b44dbc9 where the `def get_configuration_path` is declared. 

The problem occured when there's no `PYCSW_CONFIG` global environment is declared and the `get_configuration_path` defaults to the root, which does not include `default.cfg`

I can get the server to work by explicitly declare
```
PYCSW_CONFIG=/opt/pycsw/default.cfg python ./pycsw/wsgi.py
```
and the error goes away

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
Running the 4 minute installation

**Comment by tomkralidis** [comment]
@minhd thanks for the report. I've issued #529.

**Comment by tomkralidis** [comment]
Fixed in master. @minhd any chance you can verify?

**Comment by minhd** [comment]
@tomkralidis works perfectly! ❤️

**Comment by tomkralidis** [comment]
Thanks @minhd! Closing.
