### ISSUE TITLE
provide a canonical Docker image

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#530]
# Description
Provide a Docker setup in master which installs pycsw master with all dependencies.  Publish/configure to https://hub.docker.com/r/geopython/pycsw/

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by ricardogsilva** [comment]
@tomkralidis 
It seems that I cannot create an automated build on dockerhub, even if I am on pycsw's team. Perhaps you have to do it. Maybe I'll be able to tweak it once it is created?

Anyway, now that the PR is merged, when you have the time please create an automated build on dockerhub for pycsw. We could also do it together if you prefer

**Comment by tomkralidis** [comment]
@ricardogsilva.  I deleted the project on Dockerhub and re-created via creating an automated build, which seems to have worked. I added team permissions again so you should have access to adjust build settings/etc.

**Comment by ricardogsilva** [comment]
@tomkralidis thanks for that.

I still cannot do anything on docker hub though (besides seeing the repository). Must have something to do with the way docker hub assigns permissions - they are probably based on the github's repo permissions.

It would be good to configure the automated builds to:

* Build a new image with the `latest` tag whenever there is a push to `master` - This is probably already configured by dockerhub when the automated build was created
* Build a new image whenever a new tag is pushed to pycsw's repo, which will make our releases automatically available as docker images - this must be configured by us (@tomkralidis). It is fairly easy too. Just go to `Build Settings` and add a new build setting of type `Tag` (the other fields can be left as blank)

**Comment by tomkralidis** [comment]
@ricardogsilva mea culpa.  Try again?

**Comment by ricardogsilva** [comment]
@tomkralidis yes, I have access now. I've configured the build settings as described above. I'll proceed to add some docs on docker usage (I'll submit a PR with that) and after that we may close this issue

**Comment by tomkralidis** [comment]
@ricardogsilva / @kalxas are we good to close this one?

**Comment by kalxas** [comment]
+1 to close
