### ISSUE TITLE
GetRecords POST requires version and service attributes even though they are optional

### ISSUE THREAD

**Issue by andrew-wils** [geopython/pycsw#544]
# Description

The CSW schema defines the version and service parameters to be optional:
`<xsd:attribute name="service" type="ows:ServiceType" use="optional" default="CSW"/>
<xsd:attribute name="version" type="ows:VersionType" use="optional" default="3.0.0"/>`

However, sending a GetRecords POST request without them triggers the following exception:
>         <ows20:ExceptionText>Missing keyword: service</ows20:ExceptionText>

# Environment

- pycsw 2.1-dev on http://demo.pycsw.org/cite/csw

# Steps to Reproduce

HTTP POST the following:
`<?xml version='1.0' encoding='UTF-8'?>
<csw30:GetRecords xmlns:csw30="http://www.opengis.net/cat/csw/3.0">
  <csw30:Query typeNames="csw30:Record">
        <csw30:ElementSetName>full</csw30:ElementSetName>
  </csw30:Query>
</csw30:GetRecords>
`

to 

http://demo.pycsw.org/cite/csw?request=GetRecords

**Comment by tomkralidis** [comment]
@andrew-wils thanks for the report.  I've fixed this in master and 2.0 branch.  I'm surprised this wasn't caught by the OGC compliance tests for CSW 3.0.

**Comment by kalxas** [comment]
I think we can close this one now
