### ISSUE TITLE
Bring back comparing test results using difflib

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#549]
# Description

As discussed in the previous [developer meeting - Action A3](https://github.com/geopython/pycsw/wiki/Meetings-2017-10-16) it would be nice to have an extra flag for enabling diff outputs in functional tests.

I have a working branch which I'm willing to submit as a PR shortly

**Comment by kalxas** [comment]
Thanks @ricardogsilva for adding this feature to the tests.
Any suggestions on how to use this with Travis?
