### ISSUE TITLE
Harvest fails with Python 3

### ISSUE THREAD

**Issue by juozasg** [geopython/pycsw#561]
# Description
Trying to harvest from remote CSW using a POST call fails with error:  `<ows:ExceptionText>Harvest failed: record parsing failed: 'bytes' object has no attribute 'tag'</ows:ExceptionText>`

This is probably because `util.http_request` returns a `bytes` object. But `metadata._parse_metadata` checks only for `str` type.

# Environment
- operating system: OS X (Homebrew)
- Python version: 3.6.4
- pycsw version: 2.0.3
- source/distribution
  - [x] PyPI
- web server
  - [x] other (please specify): python3 pycsw/wsgi.py 

# Steps to Reproduce
curl -X POST --data-binary @sync-POST.xml 'http://127.0.0.1:8000'

```
<?xml version="1.0" encoding="UTF-8"?>
<csw:Harvest xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" service="CSW" version="2.0.2">
  <csw:Source>https://rda.ucar.edu/geoportal/csw/discovery?Request=GetCapabilities&amp;Service=CSW&amp;Version=2.0.2</csw:Source>
  <csw:ResourceType>http://www.isotc211.org/schemas/2005/gmd/</csw:ResourceType>
</csw:Harvest>
```

# Additional Information

**Comment by eblondel** [comment]
If it helps for reproducing: I got exactly the same error using docker geopython/pycsw latest image (run on OS Win 10) and using the test request https://github.com/geopython/pycsw/blob/master/tests/functionaltests/suites/default/post/Harvest-default.xml
