### ISSUE TITLE
CSW-T insert produces garbage XML

### ISSUE THREAD

**Issue by frafra** [geopython/pycsw#567]
# Description

Garbage XML is insert when adding a record using CSW-T.

# Environment

- operating system: Fedora 26 x86_64
- Python version: 3.6.2
- pycsw version: 2.0.3
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [x] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

1. Insert record via transaction (DublinCore metadata) using curl or pycsw-admin
2. Look at the database or export the record

Result:
```
\x3c6373773a5265636f726420786d6c6e733a64633d22687474703a2f2f
7075726c2e6f72672f64632f656c656d656e74732f312e312f2220786d6c6e733a6463743d226874
74703a2f2f7075726c2e6f72672f [...]
```

# Details

This is probably an encoding related bug (every character seems hex-encoded, but `\x` is used only for the first one).

pycsw is used inside Django:

```python
@csrf_exempt
def csw_wrapper(request):
    my_csw = Csw(pycsw_config, request.environ, version='2.0.2')
    http_status, response = my_csw.dispatch_wsgi()
    http_status_code = int(http_status.split()[0])
    return HttpResponse(response, status=http_status_code, content_type=my_csw.contenttype)
```

**Comment by tomkralidis** [comment]
This was since fixed in https://github.com/geopython/pycsw/commit/d631e3ec51c7fd2f16a5e37117959a88b29f98f2 and https://github.com/geopython/pycsw/commit/e25721159966f155d81d3552d195dbf405f09ce2
