### ISSUE TITLE
"Invalid Filter syntax" for all CQL_Filter requests

### ISSUE THREAD

**Issue by mohmad-null** [geopython/pycsw#569]
I'm trying to do a CQL_FILTER via a GET request, but no matter what I put as the constraint, I *always* get back an exception "Invalid Filter syntax".

These are all against the demo pycsw deployment demo.pycsw.org

I've tried:
The CQL from the GeoNetwork documentation:
https://geonetwork-opensource.org/manuals/2.10.4/eng/developer/xml_services/csw_services.html#getrecords
(That query is actually invalid anyway because it is missing the ElementSetName=full, but once you add it, you'll get the exception back)

Very basic examples built around this query:
this:
http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT

with any of these constraints:
&constraint=title%3Ddinosaur
&constraint=dc%3Atitle%3Ddinosaur
&constraint="dc:title%3Ddinosaur"
&constraint=%22dc%3Atitle%3Ddinosaur%22

&CONSTRAINT=”prop1!=10”
&CONSTRAINT=%22prop1!=10%22

The last one is copied and pasted straight from the CSW 2.0.2 spec.

Admittedly there's no real documentation out there for CQL ("pycsw cql constraint" finds nothing) so maybe my queries are wrong, but surely *one* of them should work given they appear valid, and one is in the spec. Especially after I've done the URL % encoding.

**Comment by thorsten-reitz** [comment]
Pretty much same here (I used queries that work against GeoNetwork), would be great to get some more helpful error messages instead of just "invalid filter syntax"...

**Comment by jondoig** [comment]
As mentioned [here](https://docs.pycsw.org/en/2.4.2/csw-support.html#request-examples), sample requests can be found in the [tests directory](https://github.com/geopython/pycsw/blob/master/tests): for [CSW 2.0.2](https://github.com/geopython/pycsw/blob/master/tests/functionaltests/suites/default/get/requests.txt#L8) and [CSW 3](https://github.com/geopython/pycsw/blob/master/tests/functionaltests/suites/csw30/get/requests.txt#L15).

E.g. (CSW 2.0.2): [title like '%Agriculture%'](http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT&constraint=dc%3Atitle%20like%20%27%25Agriculture%25%27)

**Comment by tomkralidis** [comment]
Hi all: I'm not able to reproduce. The following URLs return records (and not exceptions):

- http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT&constraint=dc%3Atitle%20like%20%27%25Agriculture%25%27
- http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT

Can someone test and report back with an example that can be demonstrated against http://demo.pycsw.org ?

With regard to error messages, this is by design for security purposes.  pycsw allows for server logging, which will provide deeper error messages to the administrator of the endpoint.

**Comment by jokiefer** [comment]
here some examples to reproduce:

http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT&constraint=Type=%27dataset%27

**Comment by tomkralidis** [comment]
You need to place spaces between property name, operator, and literal, and the property name needs to be bound to a namespace prefix, so:

http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT&constraint=dc:type%20%3D%20%27dataset%27

http://demo.pycsw.org/gisdata/csw?service=CSW&version=2.0.2&resultType=results&startPosition=1&maxRecords=10&typeNames=csw:Record&request=GetRecords&typeNames=csw:Record&ElementSetName=full&constraintlanguage=CQL_TEXT&constraint=apiso:Type%20%3D%20%27dataset%27

**Comment by pvgenuchten** [comment]
A note on ogcapi-records, support filter languages (for now) are :

https://github.com/geopython/pycsw/blob/3243c43c613d1fc951f3aacd6c00cbbeba119a6a/pycsw/ogc/api/records.py#L541-L542C13
