### ISSUE TITLE
Embedded commas can break "scheme" in external links

### ISSUE THREAD

**Issue by benjwadams** [geopython/pycsw#572]
# Description
Embedded commas in "links" field in PyCSW repository can result in the wrong "scheme" being loaded.
# Environment

- operating system: Ubuntu
- Python version: 2.7.6
- pycsw version: 1.10.5* (also tested locally against master branch)
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [x] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

Load/update a field with embedded commas into the repository/database into the "links" field.

This links field content was generated using `ckanext-spatial`'s `ckan-pycsw load` command on data.ioos.us, going to data.ioos.us/csw:

`ERDDAP-tabledap,ERDDAP's tabledap service (a flavor of OPeNDAP) for tabular (sequence) data. Add different extensions (e.g., .html, .graph, .das, .dds) to the base URL for different purposes.,ERDDAP:tabledap,http://erddap.cencoos.org/erddap/tabledap/noaa_nos_co_ops_prjc1`
It could also be updated manually in the database backend in the title field to test.
PyCSW joins a number of fields together using commas and carets here https://github.com/geopython/pycsw/blob/master/pycsw/core/metadata.py#L1361-L1391

The expected result would be that `ERDDAP:tabledap` would be picked up as the scheme.  However, the splitting code located at

https://github.com/geopython/pycsw/blob/d0089732c5313f0aa376c57c34f47a9b7011d7d1/pycsw/ogc/csw/csw2.py#L1504-L1514

Means that the third field separated by a comma will be picked up instead, which is ".html".

# Possible workarounds

1.  Normalize the schema by moving the links to their own table with foreign key referencing the original record.   Not sure if this is desirable as it'd require a migration of its own.

2. Denormalize and use something like Postgres's JSON or ARRAY datatypes.   This might work, but would be limited to a PostgreSQL backend, so it'd be of no assistance to users on an SQLite backend, for example.

3.  If any subcomponent contains a comma, enclose that subcomponent with a comma prior to writing to the "links" field.  When the results are being fetched from the repository, use a parser that can properly handle commas within quotes in a CSV format such as Python's built-in [csv.reader](https://docs.python.org/2/library/csv.html#csv.reader).   Unlike the previous two options, this one can work on already existing fields and will work properly with commas once the metadata is updated.

# Additional Information

Embedded caret/`^` in one of the links field could probably also break the references, since it is used to delimit separate link sections.

Original issue this occurred in and some links to Jupyter notebooks showing some some of the issues here:   
https://github.com/ioos/catalog/issues/62

**Comment by benjwadams** [comment]
I have two candidate branches based off of 1.10.5:
https://github.com/benjwadams/pycsw/tree/link_split_fix_1.10.5
and 2.2.0
https://github.com/benjwadams/pycsw/tree/link_split_fix_2.2.0

These appear to fix the aforementioned issues, but I'm going to try to add relevant tests prior to making PRs.

**Comment by tomkralidis** [comment]
Thanks @benjwadams much appreciated. I’ll help review  PRs.

**Comment by benjwadams** [comment]
@tomkralidis, unfortunately I ran into problems last night reviewing the code.

The link parsing is essentially the same as CSV parsing, but with carets as line terminators.
Pandas has a nice CSV parser, but I don't want to introduce such a heavyweight library into this codebase.
Python (in both 2 and 3) `csv.writer` can write any line terminator.  In trying to keep backwards compatibility with the currently established conventions of this library and any records already written to PyCSW repositories/DBs, I opted to keep caret as the line terminator.

However, Python's `csv.reader` can only accept \r or \n as line terminators.  From the docs:

> Note
> The reader is hard-coded to recognise either '\r' or '\n' as end-of-line, and ignores lineterminator.    This behavior may change in the future. 

Because of this, I have to substitute carets which are line terminators with '\n' or '\r'. I'm currently opting for backslash escapes instead of quote escapes because it's easier to handle the substitution with escaping newlines with backslash prior to substituting caret with newline vs. having to determine if a caret was within quotes prior to substituting.
Thus, I opted to first escape any newlines present in the string:

https://github.com/benjwadams/pycsw/blob/24f96822b6b6448781d8d8b6f5b1789d5f463bb7/pycsw/util.py#L365-L379

Now that I'm looking at it, any escaped carets should also be unescaped after carets are substituted to newline.

The main problem I encountered is that Python 2 and 3's `csv.reader` seem to have different behavior when encountering an escaped line terminator.

Consier the following snippet of code:

```python
import csv
import six
# not the original, code, but an abridged example
print(next(csv.reader(six.StringIO("should be\\\none_list?"), escapechar='\\', quoting=csv.QUOTE_NONE, quotechar=None, lineterminator="\n")))
```
When run under Python 3 this returns `['should be\none_list?']`

However, under Python 2 the same snippet returns `['should be\n']`

The Python 3 version is good enough as a hotfix to my issue listed above, but the issues with Python 2 will prevent me from making a PR in the current state.   Any other ideas on a workaround.  Perhaps use the `shlex` module?

**Comment by rsignell-usgs** [comment]
How about abandoning python 2?

**Comment by kalxas** [comment]
I don't think we can move away from Python 2, both CKAN and GeoNode are still on Python 2.

**Comment by tomkralidis** [comment]
@benjwadams thanks for the info.  Perhaps we can manage the links column as a JSON string then which would be the safest fix without massive changes to the core.  Having said this, to avoid this becoming a breaking change we would add logic to the link serializers to check if the value if JSON or not and then parse/serialize accordingly (which would ensure backward compatibility).  This change would be bound for 2.4 release. Does this sound reasonable?

echo @kalxas about requirement to keep Python 2 support.

**Comment by benjwadams** [comment]
@tomkralidis: Is it possible to revisit this now that Python 2 is no longer actively supported?

**Comment by rsignell-usgs** [comment]
Unfortunately, it looks like even though Python 2 reached end of life on January 1, 2020, CKAN is not quite there yet: https://github.com/ckan/ckan/projects/3

**Comment by tomkralidis** [comment]
@benjwadams agree/+1 to move with a py3k only approach.

**Comment by kalxas** [comment]
GeoNode 3.0 is now on Python 3.
CKAN is getting there soon.

**Comment by kalxas** [comment]
We are currently thinking of using embedded JSON in keywords field in order to fix any potential issues similar to this in the future.
