### ISSUE TITLE
create new project logo

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#577]
We've had the existing [logo](https://github.com/geopython/pycsw/blob/master/docs/_static/pycsw-logo.png) for awhile now.  Given the project's status and longevity it's a good time to update the logo to something more professional while keeping similar concepts.

**Comment by tomkralidis** [comment]
Proposals by @mandyellow in attached PDF: [brandconcept-pycsw.pdf](https://github.com/geopython/pycsw/files/2617995/brandconcept-pycsw.pdf)

**Comment by ricardogsilva** [comment]
Some very nice proposals congratulations @mandyellow.

My preference is:

1. proposal 1
1. proposal 4
1. proposal 2
1. proposal 3

**Comment by tomkralidis** [comment]
I would go with proposal 1 with some slight colour modifications to be closer to the blue we use in the current logo.

**Comment by francbartoli** [comment]
I like very much proposal 1

**Comment by kalxas** [comment]
These are all excellent proposals.
My preference:
1. Proposal 1
2. Proposal 3
3. Proposal 2
4. Proposal 4

**Comment by tomkralidis** [comment]
@mandyellow: I think we have settled on proposal 1, with the colours of proposal 3.  Can we have an update?

**Comment by mandyellow** [comment]
Sure, I'll be working on it today and reach you by Thursday. Is that okay?

Em ter, 11 de dez de 2018 12:50, Tom Kralidis <notifications@github.com
escreveu:

**Comment by tomkralidis** [comment]
Sounds good @mandyellow!

**Comment by mandyellow** [comment]
There you have it!

![teste-cores](https://user-images.githubusercontent.com/30158643/49904075-3a139200-fe50-11e8-9dd6-b614bbfd81bf.png)

**Comment by alexandreleroux** [comment]
Nice! Not sure my opinion matters, but the second one in there is my favorite. Nice work mandyellow!

**Comment by mandyellow** [comment]
Just to clarify my comment. This last proposal is, for good, the one in the middle, which is a combination of the proposal 01's format with the colors of proposal 03 as won by election on the mailling thread. :-)

**Comment by tomkralidis** [comment]
Thanks @mandyellow I think we've settled on the below (to be clear on our choice I have isolated/cropped to the image below).
![49904075-3a139200-fe50-11e8-9dd6-b614bbfd81bf](https://user-images.githubusercontent.com/910430/50218924-892f5a80-035b-11e9-87d8-70c5a416502f.png)

**Comment by kalxas** [comment]
@mandyellow can you please make a pull request with the SVG file of the new logo?

**Comment by tomkralidis** [comment]
Merged.  @mandyellow any chance we can have a favicon for https://github.com/geopython/pycsw/blob/master/docs/_static/logo/logo-symbol.png or at least instructions on how to create one?

**Comment by mandyellow** [comment]
@tomkralidis certainly!

**Comment by tomkralidis** [comment]
Closing, I think we have everything we need now to bust out our new logo.  Thanks so much @mandyellow !
