### ISSUE TITLE
update project logo across pycsw presence

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#581]
# Description
Given #577 is implemented it's time to update the new logo.  Tasks:

- [x] decide which logo(s) to use from https://github.com/geopython/pycsw/blob/master/docs/_static/logo/
- [ ] update presence
  - [x] docs
  - [x] wiki
  - [x] main website
  - [ ] OSGeoLive
  - [x] Wikipedia
  - [x] demo.pycsw.org
  - [ ] Google+ community
  - [x] Open Hub
  - [ ] others?

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
NA
# Additional Information
NA

**Comment by tomkralidis** [comment]
Update: above list almost done, awaiting pull request from https://github.com/OSGeo/OSGeoLive/pull/250 and https://github.com/OSGeo/OSGeoLive-doc/pull/443

@kalxas can you update the logo on our [Google+ page](https://plus.google.com/communities/104084873011085696113) ?  I don't have admin privileges for our G+ presence.

**Comment by kalxas** [comment]
@tomkralidis I just granted permissions to you.
I will update the logo too, thanks
