### ISSUE TITLE
Wrong xsi:schemaLocation for the xsd in csw 3.0.0?

### ISSUE THREAD

**Issue by gabrimonfa** [geopython/pycsw#593]
# Description
in CSW 3.0.0
xsi:schemaLocation="http://www.opengis.net/cat/csw/3.0 http://schemas.opengis.net/csw/3.0/cswGetCapabilities.xsd"

should the location of the xsd be modified in 
http://schemas.opengis.net/cat/csw/3.0/cswGetCapabilities.xsd?

# Environment

- operating system: Centos 7 
- Python version: 2.7.5
- pycsw version: 2.0.2
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [x] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
perform getCapabilities and look at xsi:schemaLocation

# Additional Information

**Comment by tomkralidis** [comment]
@gabrimonfa thanks very much for reporting!  Fixed in master and 2.2 branch.
