### ISSUE TITLE
load_records duplicate CRS value for ISO

### ISSUE THREAD

**Issue by ludona7** [geopython/pycsw#597]
# Description
I came across an issue with the CRS data when using the [`load_records`](https://docs.pycsw.org/en/1.8.1/administration.html#loading-records) method, specifically when importing ISO records.

Once imported, I found that my database stored values in `records.crs` like this:

`urn:ogc:def:crs:EPSG:6.11:urn:ogc:def:crs:EPSG::4326`

Inspecting the code in https://github.com/geopython/pycsw/blob/master/pycsw/core/metadata.py#L1245, it prepends `urn:ogc:def:crs:EPSG:6.11` to the value of `referenceSystemIdentifier.RS_Identifier.code` of the source XML file.

This works in cases where just the 'number code' is defined in `referenceSystemIdentifier.RS_Identifier.code` (e.g. 4326), but I found that some of the records I wanted to import (rightly or wrongly) have the whole value like: `urn:ogc:def:crs:EPSG:6.11:4326` sometimes with or without a version.

I've created a patch on my instance that should now cater for all the possible formats it might receive when it loads the records into pycsw - (ie. just the num code, the full string with or without a version).

I've also removed the hardcoded 'version' (6.11) that was being prepended, and replaced with the extracted 'version' from the value of `<gmd:code>`, or if `<gmd:version>` is defined, it takes it from here instead.

I will create a PR in case you think this is useful more generally.

# Environment

- operating system: CentOS 7.5.1804
- Python version: 3.4.9
- pycsw version: 2.2.0
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [x] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): nginx/gunicorn

# Steps to Reproduce

Run `load_records` function where the input XML file is ISO and contains a 'full' reference in the `referenceSystemIdentifier.RS_Identifier.code` element, e.g `urn:ogc:def:crs:EPSG::4326`

# Additional Information

**Comment by tomkralidis** [comment]
@ludona7 thanks for the report.  Would something like the below work?

```python
    if md.referencesystem is not None:
        try:
            code_ = 'urn:ogc:def:crs:EPSG:6.11:%d' % int(md.referencesystem.code)
        except ValueError:
            code_ = md.referencesystem.code
        _set(context, recobj, 'pycsw:CRS', code_)
```

**Comment by ludona7** [comment]
Hi @tomkralidis. Yes this fixes the duplication problem in the database nicely. 

It doesn't detect if a 'version' is also supplied in it's own field (`md.referencesystem.version`), instead it defaults to 6.11, which may not always be correct. But perhaps this should be made into a new separate issue rather than trying to fix two things at once. 

If the 'version' is supplied as part of the `md.referencesystem.code` value, then obviously this still works fine.

Considering that the 'version' is optional, I've opted for:

```python
    if md.referencesystem is not None:
        try:
            code_ = 'urn:ogc:def:crs:EPSG::%d' % int(md.referencesystem.code)
        except ValueError:
            code_ = md.referencesystem.code
        _set(context, recobj, 'pycsw:CRS', code_)
```

So it's the same, but I omit the hardcoded `6.11`, in case this is incorrect.

**Comment by tomkralidis** [comment]
Sounds good @ludona7.  Are you able to provide a pull request?
