### ISSUE TITLE
ISO metadata failed to load "metadata not-supported"

### ISSUE THREAD

**Issue by epifanio** [geopython/pycsw#604]
# Description
I have a xml metadata record which is supposed to be in ISO standard fiormat but it fails to load as it is considered of ` type not-supported `

An example file is avaialble as gist [here](https://gist.github.com/epifanio/7713ec0afd669c769016b50c0e8e9d23)

it should be a `<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd">`
which is supposed to be [compatible](http://docs.pycsw.org/en/stable/transactions.html)

this the pycsw log: 
```
Could not parse "S1A/S1A_IW_GRDM_1SDV_20190914T164935_20190914T164959_029020_034ADB_E2E5.xml" as an XML record
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pycsw-2.5.dev0-py3.7.egg/pycsw/core/admin.py", line 348, in load_records
    record = metadata.parse_record(context, exml, repo)
  File "/usr/local/lib/python3.7/dist-packages/pycsw-2.5.dev0-py3.7.egg/pycsw/core/metadata.py", line 119, in parse_record
    return _parse_metadata(context, repos, record)
  File "/usr/local/lib/python3.7/dist-packages/pycsw-2.5.dev0-py3.7.egg/pycsw/core/metadata.py", line 158, in _parse_metadata
    raise RuntimeError('Unsupported metadata format')
RuntimeError: Unsupported metadata format
```

# Environment

- operating system:

Linux - debian sid
- Python version:

- pycsw version:

```
Python 3.7.4+ (default, Sep  4 2019, 08:03:05) 
[GCC 9.2.1 20190827] on linux

```
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [X] other (please specify): 

`gunicorn pycsw.wsgi`

# Steps to Reproduce

```
python3 pycsw-admin.py -c load_records -f /etc/pycsw/pycsw.cfg -p test.xml
```

# Additional Information
it seems that the compatibility issue is due to the use of following `xmlns` namespace schema:
```
<record xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

**Comment by epifanio** [comment]
I "kind of" get it to work, by manually changing the xml file.

I had to remove the `<record>`, `<header>`, and `<metadata>` tags and by including 
```
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```
directly into the `<gmd:MD_Metadata>` tag.

So that the first line of the `xml` file changed from:

```
<record xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><header><identifier>S1A_EW_GRDH_1SDH_20190116T174616_20190116T174734_025506_02D3FA_14A9</identifier><datestamp>2019-01-16T18:00:35Z</datestamp><setSpec>NBS</setSpec></header><metadata>
```

To:

```
<?xml version="1.0" encoding="utf-8"?>
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```


Still not perfect, this is what *QGIS MetaSearch* returns, when loading such record:
 


Identifier | S1A_EW_GRDH_1SDH_20190116T174616_20190116T174734_025506_02D3FA_14A9
-- | --
Title | Date: 2019-01-16T17:46:16.076Z, Instrument: SAR-C SAR, Mode: HH HV, Satellite: Sentinel-1, Size: 1.3 GB
Abstract | The SENTINEL-1 mission comprises a constellation of two polar-orbiting satellites, operating day and night performing C-band synthetic aperture radar imaging, enabling them to acquire imagery regardless of the weather.
Subjects | climatologyMeteorologyAtmosphere
Creator | None
Contributor | None
Publisher | None
Modified | 2019-01-16T18:00:35.325Z
Language | None
Format | None
Rights |  
Bounding Box | -16.39,68.04,-1.56,73.58


* OPeNDAP 
* URI to GetCapabilities Document. 
* but should point directly to the data file or a catalogue containing the data. 
* ODATA

**Comment by tomkralidis** [comment]
@epifanio can you send a sample test case/record?

**Comment by epifanio** [comment]
An example XML file is available as a gist at this link:

https://gist.github.com/epifanio/7713ec0afd669c769016b50c0e8e9d23

It seems to be a problem on our side as the ```xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"``` is outside the metadata tag. However, once this is fixed at the metadata source by including the  ```xsi="http://www.w3.org/2001/XMLSchema-instance"``` into the metadata tag.

However, the harvesting of the records directly from the OAIMPH endpoint is not possible because I still need to remove the `record` and `header` child from the XML to get it to work in `PyCSW` -- this means I can't use the `Transaction=True` feature, to  harvest records directly from `OAIMPH` endpoint URL. @tomkralidis is that correct? What would be a way to have direct harvesting in PyCSW from such endpoint-URL? For now, I think I will get the XML response, parse it and then pass it to `PyCSW`.

**Comment by tomkralidis** [comment]
@epifanio thanks for the info.  Correct; this would require pycsw to support harvesting from an OAI-PMH endpoint, which would be an enhancement. Feel free to file a issue/ticket for further discussion.  Your workaround in the meantime makes sense.
