### ISSUE TITLE
Looking for help configuring a GetCapabilities response document

### ISSUE THREAD

**Issue by PeterParslow** [geopython/pycsw#607]
# Description
I’m testing a CSW implemented with pycsw (as a CKAN plugin) to run an INSPIRE Discovery Service.

The one I'm testing is at https://ckan.publishing.service.gov.uk/csw?REQUEST=GetCapabilities&SERVICE=CSW&VERSION=2.0.2

It fails INSPIRE Dvalidation (https://github.com/inspire-eu-validation/community/issues/211).

Two of the possible causes are:

1. The document only declares the "inspire_ds" XML namespace (http://inspire.ec.europa.eu/schemas/inspire_ds/1.0) by means of a local xsi:schemaLocation attribute on the inspire_ds:ExtendedCapabilities element.

How can I configure the pycsw GetCapabilities response document to declare the schemaLocations in the root element, as suggested by Iurie (https://github.com/inspire-eu-validation/community/issues/211#issuecomment-583489179)

2. The XML processing instruction declares "standalone = 'no'", which is at best unnecessary, and may be causing the validating parser to go looking for a DTD!

Again, how can I configure that out?
# Environment

# Steps to Reproduce
Run the INSPIRE Validator on this end point

# Additional Information
I can’t see a documented way to change the GetCapabilities response document.
The FAQ mentioned at https://pycsw.org/community/ has gone, as has the Google+ group (but that was Google). 
I've had no response by sending this to the pycsw-devel@lists.osgeo.org email list!
Perhaps someone could fix these broken things

Finally, someone on the INSPIRE forum pointed me to this repository as I place I might get help.

**Comment by tomkralidis** [comment]
@PeterParslow thanks for the report.  The XML is valid and the output at that level (changing namespaces and such) is not configurable.  In our Capabilities XML response, we "lazy" add INSPIRE support as part of our APISO plugin.

Having said this, when I run https://ckan.publishing.service.gov.uk/csw?REQUEST=GetCapabilities&SERVICE=CSW&VERSION=2.0.2 through a validating parser, I see the following errors:

- `<inspire_common:MetadataDate>YYYY-MM-DD</inspire_common:MetadataDate>`
- `<inspire_common:EmailAddress>Email Address</inspire_common:EmailAddress>`
- `<inspire_common:StartingDate>YYYY-MM-DD</inspire_common:StartingDate>`
- `<inspire_common:EndDate>YYYY-MM-DD</inspire_common:EndDate>`

If I update the content (locally of course) then the document validates with no issue.

A workaround could be to write your own intercept of the pycsw Capabilities response, update the XML in memory and send back accordingly.

**Comment by tomkralidis** [comment]
@PeterParslow with regard to community interactions:
- I've removed the Google+ link (thanks for reporting)
- I've updated the broken link to the FAQ page (thanks for reporting)
- for the email list, I don't see any emails in https://lists.osgeo.org/pipermail/pycsw-devel from yourself, nor any administrative emails on bounces.  Can you try subscribing and sending an email?

**Comment by PeterParslow** [comment]
Thanks Tom, I realise now that I hadn't completed the "join the mailing list" formalities. I've resent it now.

I will share the view that the XML is valid back on the GitHub issue where it's been suggested I fix it! I do agree that declaring the namespace locally is valid, and so far my view is also that stating 'standalone = no' shouldn't be harmful.
