### ISSUE TITLE
optimize Dockerfile

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#614]
# Description
cc @epifanio @ricardogsilva 

Carrying on from https://github.com/geopython/pycsw/pull/613#pullrequestreview-407505149, find ways to speed up build, reduce image size, and testing.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
NA

# Additional Information
NA

**Comment by tomkralidis** [comment]
@ricardogsilva the following test builds in 40 seconds but creates an image of 334MB.  Any ideas to reduce the size?

```
FROM python:slim-buster
LABEL maintainer="massimods@met.no,aheimsbakk@met.no"

ARG PYCSW_HOME=/tmp/pycsw

ENV PYCSW_CONFIG=/etc/pycsw/pycsw.cfg

COPY . ${PYCSW_HOME}

RUN apt-get update && apt-get install -y ca-certificates

RUN pip3 install --upgrade pip setuptools \
  && pip3 install wheel \
  && pip3 install gunicorn \
  && pip3 install --requirement ${PYCSW_HOME}/requirements.txt \
  && pip3 install --requirement ${PYCSW_HOME}/requirements-standalone.txt \
  && pip3 install --requirement ${PYCSW_HOME}/requirements-pg.txt

ADD docker/pycsw.cfg ${PYCSW_CONFIG}
ADD docker/entrypoint.py /usr/local/bin/entrypoint.py

WORKDIR ${PYCSW_HOME}

RUN pip3 install . \
  && useradd -ms /bin/bash pycsw \
  && cp -r ${PYCSW_HOME}/tests /home/pycsw \
  && chown -R pycsw:pycsw /home/pycsw/* \
  && rm -rf /usr/lib/python3*/*/tests \
  && rm -rf /usr/lib/python3*/ensurepip \
  && rm -rf /usr/lib/python3*/idlelib \
  && rm -f /usr/lib/python3*/distutils/command/*exe \
  && rm -rf /usr/share/man/* \
  && rm -fr ${PYCSW_HOME} \
  && find /usr/lib -name  "*.pyc" -o -name "*.pyo" -delete

WORKDIR /home/pycsw

EXPOSE 8000

USER pycsw

ENTRYPOINT [ "python3", "/usr/local/bin/entrypoint.py" ]
```

**Comment by ricardogsilva** [comment]
@tomkralidis I'm a bit swamped at the moment, but if you can give me a couple of days to look into it, I hope to be able to provide some assistance

**Comment by ricardogsilva** [comment]
@tomkralidis see my PR #615 for my take on this.

I wasn't able to slim the image too much, currently with 311MB, but IMHO it would be better for pycsw to be on a debian base. I leave it up to your consideration and lets discuss this further, if needed.
