### ISSUE TITLE
Support for multiple occurences of attributes

### ISSUE THREAD

**Issue by Rastopapola** [geopython/pycsw#617]
# Description
According to the source code pycsw iterates over a `,` separated string and creates individual elements for each item in case of `dc:subject`. 
```python
file: csw2.py, line 1484 following

                keywords = util.getqattr(recobj, queryables['dc:subject']['dbcol'])
                if keywords is not None:
                    for keyword in keywords.split(','):
                        etree.SubElement(record,
                        util.nspath_eval('dc:subject',
                        self.parent.context.namespaces)).text = keyword
```

I expected the same behaviour for all identifiers, that are stated to have `0...n` occurences according to the specification of CSW.
![image](https://user-images.githubusercontent.com/35961376/81921077-58983280-95da-11ea-9a0b-7ce4e486630d.png)

But surprisingly this is not the case, as I get for my records the following:

```xml
...

<dc:format>image/png,image/tiff,image/jpeg,image/png; mode=8bit,image/vnd.jpeg-png,image/vnd.jpeg-png8,application/x-pdf,image/svg+xml,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz,application/x-protobuf,application/json,application/vnd.ogc.wms_xml,text/plain,application/vnd.ogc.gml,text/xml,image/png,image/jpeg,image/png; mode=8bit,image/vnd.jpeg-png,image/vnd.jpeg-png8,text/xml</dc:format>
...
<dct:spatial scheme="http://www.opengis.net/def/crs">EPSG:31466,EPSG:31467,EPSG:25832,EPSG:4326,EPSG:4258,EPSG:3857</dct:spatial>
```

A closer look in the source code reveals the reason for this:
```python
file: csw2.py, line 1497 following

                val = util.getqattr(recobj, queryables['dc:format']['dbcol'])
                if val:
                    etree.SubElement(record,
                    util.nspath_eval('dc:format',
                    self.parent.context.namespaces)).text = val

```

Is it possible to add support for these attributes, just like for keywords? Or is it already implemented in a newer version of pycsw, that is not available using pip, yet?

# Environment

- operating system: Deb10 Buster
- Python version: 3.7
- pycsw version: 2.4.2
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [x] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): Django Dev Webserver

# Steps to Reproduce

Not directly a bug, therefore no steps to reproduce

# Additional Information
 ~~None~~

**Update:**
I use pycsw in an own project as read-only API for my metadata records. The metadata is not stored completely in one table but distributed over several tables like `Keyword`, `SpatialReferenceSystem` and so on to make the database more flexible. 

For the mapping of expected columns for the CoreMetadata model of pycsw I added some mocked columns to my Metadata model class which allow me to create custom return values for the non-existing columns, e.g. the keywords. 

As seen in the source code of pycsw I return in all my M2M relations (which are represented by the mocked columns) the relation element's names in a string, using `,` as delimiter. This works for the keywords pretty fine but not for other attributes.

**Comment by tomkralidis** [comment]
@Rastopapola thanks for the report.  Do you have sample metadata so I can reproduce ?  pycsw only supports output of multiple occurrences of attributes for specific properties (like subjects/keywords, links), which are dependent on the input metadata.  Having said this, if you update, say, a Dublin Core document with multiple repeated properties, search results (with `elementsetname=full` and Dublin Core as the output) will return the DC document as inserted.

**Comment by Rastopapola** [comment]
@tomkralidis thanks for the fast reply.
I hooked up pycsw as an interface for my own database, where the metadata records do not hold all data directly in one table. E.g. keywords are stored in an own table as individual records and refer to their described metadata using M2M relations and so on. That's why I can not provide any metadata for reproducing the behaviour. 

As far as I understood from the source code e.g. the keywords are expected to be returned for the xml building as one larger string, where all keywords are separated using `,`.  Therefore I implemented the same behaviour for other attributes, like the supported spatial reference systems, which should be stored in `dc:spatial`.

What I did is basically mocking the table properties, using model functions decorated with `@property`. So I could for example create a single string from all related keywords, which works fine. But the same way does not work for other elements with possibly multiple occurences like formats, which would appear in `dc:format`.

I'm not sure if I only need another delimiter for my returned strings - but I could not see any hint on that in the source code.

**Comment by tomkralidis** [comment]
@Rastopapola the pycsw data model as it stands is not built for these constructs beyond some fields (keywords, links) -- see https://docs.pycsw.org/en/latest/administration.html#existing-repository-requirements for more info.

For example, you could patch the code above to additionally output multiple occurences of a field given a comma-separated list, but then you would have to additionally make this work across the rest of the outputs (ISO, FGDC, DIF, Atom, etc.).  Then again if core CSW is good enough, then this may be a moot point.

Having said this, an easier workaround would be to serialize and store a Dublin Core document (with multiple occurences, etc. as you wish) in a text field and map the `pycsw:XML` mapping to that field.  Then, CSW requests like: https://example.org/csw?service=CSW&version=2.0.2&request=GetRecords&typenames=csw:Record&elementsetname=full&resulttype=results (note that `elementsetname=true` triggers pycsw to look for the `pycsw:XML` field/mapping and dump that file back to the client, as opposed to serializing the XML) would work.

**Comment by Rastopapola** [comment]
@tomkralidis Thanks for your feedback!

>the pycsw data model as it stands is not built for these constructs beyond some fields (keywords, links)

So it's expected that one metadata record holds exactly one e.g. format, since multiple `dc:format` elements would not be supported directly using the MD_CORE_MODEL mapping approach?

Thanks for your suggestions. I may write a patch covering this feature.

**Comment by Rastopapola** [comment]
@tomkralidis For now I'm only going to extend `pycsw:Format` and `pycsw:CRS`. Could I create a branch for this or do you have to create one?

**Comment by tomkralidis** [comment]
Feel free to fork and create a branch.  You can submit a PR thereafter for review.

**Comment by Rastopapola** [comment]
Pull request has been created and checks have been passed successfully. #618

**Comment by Rastopapola** [comment]
@tomkralidis 
I was writing tests when I noticed something really bad: pycsw is using the owslib, which doesn't seem to allow multiple formats as well:

```python
file: iso.py, line 657
...
class MD_Distribution(object):
    """ process MD_Distribution """
    def __init__(self, md=None):
        if md is None:
            self.format = None
            self.version = None
            self.distributor = []
            self.online = []
            pass
        else:
            val = md.find(util.nspath_eval(
                'gmd:distributionFormat/gmd:MD_Format/gmd:name/gco:CharacterString', namespaces))
            self.format = util.testXMLValue(val)
...
```
As you can see, the MD_Distribution object takes a single value - more precisely: the first value and ignores other existing formats. This is pretty bad, since it does not follow the specifications for ISO19115, 19119 or 19138, which allows a multiplicity of * for the format objects.

This means I would have to write a patch for the owslib, which has to be accepted and merged, afterwards I can continue the work on here. 

Since our use case for the CSW interface is pretty simple, the work I invest in here outgrows the benefits. The easiest for me would be to write an own interface, which covers the requirements of our use case.

I'm sorry, you might do with the Pull request whatever you like but it's not sufficient to crawl deeper and change even more third party packages. 

Anyway, thanks for your help!
