### ISSUE TITLE
Can't load metadata on windows

### ISSUE THREAD

**Issue by kishkumar96** [geopython/pycsw#620]
# Description
Hi I'm trying to load metadata on pycsw but whenever I try to run the below command or any other command that uses pycsw-admin.py the system opens up the visual studio code with the pycsw-admin file instead of excuting the command. Can someone teach how to deal with this please 
# Environment

- operating system: Windows
- Python version: 3.7.6
- pycsw version: 2.5
- source/distribution
  - [ *] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
1. git clone
2. Following the setup database section on the website
# Additional Information

**Comment by tomkralidis** [comment]
Please post questions to the pycsw mailing list. pycsw's GitHub issues are for **software bugs/enhancements** and related tasks.
