### ISSUE TITLE
DataCite output schema

### ISSUE THREAD

**Issue by cfenell** [geopython/pycsw#623]
i all,
We (https://www.eiscat.se)  plan to provide metadata to B2Find, http://b2find.eudat.eu, so we are looking to set up an OAI-PMH server and I found pycsw.

It would be good to be able to serve both DublinCore and DataCIte, and I found an email thread from 2018 about adding DataCite to the output schemas.
Was there any progress on this? If not I would be willing to contribute, thankful for directions where to start.
Best regards Carl-Fredrik

**Comment by cfenell** [comment]
There is a plugin that produces a bare minimum of DataCite records at [](https://github.com/cfenell/pycsw/blob/datacite/pycsw/plugins/outputschemas/datacite.py)
I plan to extend on it and create a proper fork and pull request when I have tested it.

**Comment by pvgenuchten** [comment]
Thanks for the initial work @cfenell, we're interested in this development also.

Some extra resources are:
- datacite profile in [openaire](https://guidelines.openaire.eu/en/latest/data)
- a [python library](https://pypi.org/project/datacite/) to create datacite metadata

**Comment by cfenell** [comment]
Hi, thanks a lot for taking up this project!
I am afraid I have not done anything here recently, but had planned to return to it before [EISCAT 3D]( https://eiscat.se/eiscat3d-information/) starts producing data during next year.
I'll be happy to look at your work and test it, and not least to have a good Python library for writing DataCite metadata.

What we have done so far about DataCite is:
Data from our old systems can be browsed through the [Schedule](https://portal.eiscat.se/schedule/):
- select Archived Data
- click Query
-  click ranges of blue "A":s
You will then be redirected to a system called Madrigal, where data are archived in files called MADxxx.hdf5
There are also  attached supplemental  files EISCAT_yyyy-mm-dd....hdf5, which are the original data in our own format with an added dataset  /metadata/schemes/DataCite. 
Our legacy system however uses Matlab to produce these files and I am looking for an open source replacement for the future. The data and metadata formats to be used in EISCAT 3D are still very much TBD, but the possibility to write DataCite metadata from Jupyter notebooks will almost certainly be required and we still consider to provide OAI-PMH harvesting.

**Comment by pvgenuchten** [comment]
@cfenell, this is now ready to be reviewed, welcoming your thoughts (for example about the use of contentUrl)

**Comment by kalxas** [comment]
Looks good, thanks for the contribution!
