### ISSUE TITLE
Error when call harvest with respondHandler after fix #666

### ISSUE THREAD

**Issue by Jrmy-Msn** [geopython/pycsw#667]
# Description
After fix #666 
New error comes on FTP process.

Trace ...
site-packages/pycsw/server.py", line 862, in _process_responsehandler
    ftp.storbinary('STOR %s' % uprh.path[1:], StringIO(xml))
TypeError: initial_value must be str or None, not bytes

effectively, when I log type(xml) it return <class bytes>

If I replace StringIO by BytesIO, it works

best regards

# Environment

- operating system:
- Python version: 3.7
- pycsw version: 2.6
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [x ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by tomkralidis** [comment]
Thanks for the report. Can you provide an example XML request to help reproduce?
