### ISSUE TITLE
Support OGC API - Records

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#670]
# Description

Add implementation for OGC API - Records:
https://ogcapi.ogc.org/records/
https://github.com/opengeospatial/ogcapi-records

# Implementation Options

- [x] Implement a new wsgi application based on Flask to use routing
- [x] Add core implementation in pycsw/ogc/api
- [x] Plug the new API to the existing configuration
- [x] Plug the new API to the existing repository/model
- [x] Add OpenAPI support
- [x] Add JSON output support
- [x] Add HTML output support
- [x] Add XML output support
- [x] Add CQL support via pycql
- [x] Support attribute/datetime queryables
- [x] Support bbox queries
- [x] Support anytext queries
- [x] Add alternative CSW route under /csw
- [x] Update Docker setup
- [x] Add map widget to records HTML
- [x] Add link relations
- [x] Add tests
- [x] Add documentation
- [ ] Support CQL JSON

**Comment by kalxas** [comment]
Implementation in progress:
https://github.com/geopython/pycsw/tree/oarec

**Comment by kalxas** [comment]
no, dockerfile is not updated yet

**Comment by kalxas** [comment]
@KoalaGeo  please use the geopython/pycsw:oarec docker image to test

**Comment by tomkralidis** [comment]
Notes:
- a pycsw OARec capability would require the `PYCSW_CONFIG` environment variable so as to keep the base URL simple.  Given we are breaking master we could consider having this behaviour even for CSW 2/3 (thus removing support for `config=/path/to/default.cfg`)
- I've added some initial tests (requests) in https://github.com/geopython/pycsw/blob/oarec/tests/functionaltests/suites/oarec/get/requests.txt however I'm not quite sure how to run tests.  @ricardogsilva given your awesome work on upgrading the tests to pytest, any insight or suggestions here?  How would you see this working.  Would this be an opportunity to introduce testing closer to the spirit of pytest (for example how we do in [pygeoapi API testing](https://github.com/geopython/pygeoapi/blob/master/tests/test_api.py) as opposed to the C14N / byte level testing as we currently do with XML responses)?

Once tests are done and docs updated I think we are close to done.

**Comment by tomkralidis** [comment]
Implemented in master.
