### ISSUE TITLE
OAI-PMH ListIdentifiers returns list of identical identifiers

### ISSUE THREAD

**Issue by epifanio** [geopython/pycsw#677]
# Description
Query a `pycsw` catalog using the `oaipmh` with the `verb` : `ListIdentifiers` returns a list of identical identifiers.

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
Query any `pycsw` endpoint using the `oaipmh` with the `verb` : `ListIdentifiers`

e.g.: https://catalog.data.gov/csw?mode=oaipmh&verb=ListIdentifiers&metadataPrefix=dif

# Additional Information

**Comment by tomkralidis** [comment]
@epifanio fixed in master.  Can you test/validate?

**Comment by epifanio** [comment]
Tested master, i confir this chages are fixing the issue, thanks!!!
