### ISSUE TITLE
The lastest version (8b8bb0dc9f61) will cause anytext query error when using QGIS metasearch client and owslib.

### ISSUE THREAD

**Issue by scku208** [geopython/pycsw#692]
# Description
    Use the lastest version docker tag (8b8bb0dc9f61) will cause anytext query error.
# Environment

- operating system: ubuntu 16.04LTS docker
- Python version: 3.8.10 from docker container
- pycsw version: The lastest version (8b8bb0dc9f61)
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [x] other (please specify): docker hub
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): docker container default server(?)

# Steps to Reproduce
docker compose up -d with some basic configuration (server.url)
use QGIS or owslib to getrecords with search or some anytext query

# Additional Information
1. I have a nginx server in front of it to proxy_pass pycsw
2. If I rollback pycsw to version 2.8.0-alpha2, everything goes well.
3. http get method seems fine ( getRecords, see below figure )

Thanks you for developing this great tool!

latest (8b8bb0dc9f61)
![image](https://user-images.githubusercontent.com/10119552/121777044-ae1a8680-cbc2-11eb-93df-9e41f9949ced.png)
The query error from qgis3-16.7
![image](https://user-images.githubusercontent.com/10119552/121777002-7d3a5180-cbc2-11eb-8f7d-1de3663cfbc3.png)
The error from owslib-0.24.1
![image](https://user-images.githubusercontent.com/10119552/121777152-1d907600-cbc3-11eb-9a9c-feaafc40e780.png)

2.8.0-alpha2 (which use slightly different command: `pycsw-admin.py -c get_sysprof`)
![image](https://user-images.githubusercontent.com/10119552/121776967-4c5a1c80-cbc2-11eb-98d1-bb8d2d029b54.png)

get demo records from http
![image](https://user-images.githubusercontent.com/10119552/121777612-95f83680-cbc5-11eb-91b4-138e10a26634.png)

**Comment by tomkralidis** [comment]
Thanks for the report.  This was fixed by #694 -- can you test again/validate against current master?

**Comment by scku208** [comment]
> Thanks for the report. This was fixed by #694 -- can you test again/validate against current master?

@tomkralidis Thanks for your help, it works like a charm!

I also found my mistake: 
    The correct csw service url should be `http://{host}/csw`, (I used `http://{host}/` before).
b/s in version 2.8, csw service by url `http://{host}/` also works.
but in version latest (3?), url `http://{host}/` becomes a nice pycsw homepage (and a lot of new feature?) \-皿-/ (hurray

 I appreciate your kind assistance.

**Comment by tomkralidis** [comment]
Great!  Yes, depending on how you setup pycsw (looks like you deployed via `pycsw/wsgi_flask.py`), [OGC API - Records](https://ogcapi.ogc.org/records) support is the default endpoint.
