### ISSUE TITLE
Loading of OGC API - Records JSON to pycsw directly

### ISSUE THREAD

**Issue by ShaneMill1** [geopython/pycsw#704]
I have recently started working with pycsw as an implementation of OGC API - Records. It seems that pycsw takes csw records, loads them into a database, and then pycsw has some logic to translate that csw record into an OGC API Record. Could it be possible in the future to load an OGC API - Records JSON into pycsw directly instead of a csw record?

**Comment by kalxas** [comment]
This is now supported in master
