### ISSUE TITLE
Enabling federated search

### ISSUE THREAD

**Issue by epifanio** [geopython/pycsw#729]
# Description

Query to a CSW endpoint with `federated search` enabled into the pycsw config and in the service request (`distributedsearch=TRUE`) doesn't return the expected records. The service seems to ignore the  federated search option and returns  the records available from the default CSW configuration (e,g: same as per `distributedsearch=FALSE`)

# Environment

- operating system:
    Linux Ubuntu server 20.04
- Python version:
   3.8
- pycsw version:
  git master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 
    Flask app

# Steps to Reproduce

Pycsw config
```
[server]
...
federatedcatalogues=https://nbs.csw.met.no/csw?config=/etc/pycsw/pycsw.cfg,https://adc.csw.met.no/csw?config=/etc/pycsw/pycsw.cfg,https://sios.csw.met.no/csw?config=/etc/pycsw/pycsw.cfg
```

The following URL list the same number of records as the federated search was not enabled 

Example [Request](https://tstsios.csw.met.no/csw?service=CSW&version=2.0.2&request=GetRecords&typenames=csw:Record&elementsetname=full&resulttype=results&distributedsearch=TRUE&)

# Additional Information

CC @tomkralidis

**Comment by tomkralidis** [comment]
thanks for the report @epifanio.  I'm able to reproduce; traceback:

```
Mon, 18 Apr 2022 16:23:09] [ERROR] file=/Users/tomkralidis/Dev/pycsw/lib/python3.7/site-packages/pycsw-3.0.dev0-py3.7.egg/pycsw/ogc/csw/csw2.py line=881 module=csw2 function=getrecords remote CSW https://nbs.csw.met.no/csw?config=/etc/pycsw/pycsw.cfg returned error: 
Traceback (most recent call last):
  File "/Users/tomkralidis/Dev/pycsw/lib/python3.7/site-packages/pycsw-3.0.dev0-py3.7.egg/pycsw/ogc/csw/csw2.py", line 857, in getrecords
    outputschema=self.parent.kvp['outputschema'])
  File "/Users/tomkralidis/Dev/pycsw/lib/python3.7/site-packages/owslib/catalogue/csw2.py", line 337, in getrecords2
    if xml.startswith(b'<'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

A [fix](https://github.com/geopython/OWSLib/pull/776) was committed to OWSLib as part of federated search updates in May 2021 is needed in OWSLib.

A resulting [fix](https://github.com/geopython/OWSLib/pull/816) has been pushed in OWSLib, to handle either `bytes` or `str` input in OWSLib.

@epifanio can you validate the fix with pycsw using OWSLib master?  We can then issue an OWSLib release once validated.

**Comment by tomkralidis** [comment]
FYI tested and validated at the pycsw May 2022 code sprint.
