### ISSUE TITLE
pycsw demo server error causes CI to break

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#736]
# Description

pycsw demo server logs this:
![image](https://user-images.githubusercontent.com/383944/158053170-5e8b0308-d677-48b3-8c24-1928aab22928.png)

**Comment by kalxas** [comment]
Error reported also in GeoNode gitter:
![image](https://user-images.githubusercontent.com/383944/158053204-99479ca8-654c-4129-8d1d-4220b415589e.png)

**Comment by kalxas** [comment]
https://bugs.launchpad.net/ubuntu/+source/expat/+bug/1961800

**Comment by kalxas** [comment]
![image](https://user-images.githubusercontent.com/383944/158053242-c7bc2d8c-289b-4dbc-9269-1c1443b40f26.png)

**Comment by kalxas** [comment]
https://github.com/libexpat/libexpat/issues/572

**Comment by kalxas** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006317

**Comment by kalxas** [comment]
https://github.com/libexpat/libexpat/pull/577

**Comment by afabiani** [comment]
@kalxas consider this fix for pycsw
https://github.com/OpenLEADR/openleadr-python/pull/105/files

it looks related to the namespace separator

**Comment by kalxas** [comment]
thanks @afabiani we will take a look
this is where the issue is:
https://github.com/geopython/pycsw/blob/master/pycsw/core/formats/fmt_json.py#L60-L69

**Comment by afabiani** [comment]
@kalxas it looks to me that the `libexpat1/focal-updates,focal-security 2.2.9-1ubuntu0.4` version however does not present the issue anymore. Doing some tests.

**Comment by kalxas** [comment]
Thanks, this has been fixed
