### ISSUE TITLE
Add pycsw to DebianGIS

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#75]
I will follow up on contacting debiangis people to get this done...

**Comment by tomkralidis** [comment]
@johanvdw FYI this is being discussed on the OSGeo Standards mailing list: http://osgeo-org.1560.x6.nabble.com/OGC-XML-schemas-and-FOSS4G-software-distribution-td5186023.html

**Comment by johanvdw** [comment]
Pycsw is now part of Debian unstable and testing (stretch, next release).
It also migrated to ubuntu for the "wily" release.
https://packages.debian.org/sid/python-pycsw
https://launchpad.net/ubuntu/+source/pycsw

Note that beause of the ongoing discussion on the "freeness" of the OGC standard documents pycsw is part of "non-free" in debian and "multiverse" on ubuntu.

**Comment by tomkralidis** [comment]
Thanks @johanvdw.  I think the following needs to be updated / is unclear?

`This package contains the necessary backend Python scripts for running the Apache cgi plugin (python-pycsw-wsgi). `

**Comment by kalxas** [comment]
Thanks @johanvdw

**Comment by johanvdw** [comment]
@tomkralidis : Feel free to suggest another wording. I'll import the new version soon, so I can update the description at that time.

**Comment by tomkralidis** [comment]
@johanvdw does `python-pycsw` come with the CSW endpoint/script?  Suggested changes:

1. `OGC compliant metadata (Catalogue Services for the Web) server`
2. `This package contains the necessary backend Python scripts for running the Apache mod_wsgi plugin (python-pycsw-wsgi). `

**Comment by johanvdw** [comment]
Tom: Updated.https://packages.debian.org/sid/python-pycsw-wsgi

**Comment by kalxas** [comment]
nice, perhaps we should close this issue?

**Comment by tomkralidis** [comment]
thanks @johanvdw small typo in https://packages.debian.org/sid/python-pycsw (i.e. `s/Catalogue service for the Web/Catalogue Service for the Web)/ `

@kalxas should we add this to the [docs](http://docs.pycsw.org/en/latest/installation.html) and [download page](http://pycsw.org/download/)?

**Comment by kalxas** [comment]
This deb package is only available in Sid, which means it is not available for a released Debian version yet. It would be misleading to users to include this in the docs, unless we specifically state that it is only available in Sid.

**Comment by tomkralidis** [comment]
OK.  So we wait until next Debian release?

**Comment by kalxas** [comment]
We could add it to the download page as "Debian (Sid only)" and update docs when the next Debian release happens

**Comment by johanvdw** [comment]
We can also add it to debian-backports, so people using jessie can install
from there.

I'll wait until this version hits testing and see if I can add it to
backports.We can update the instructions if it is done.

**Comment by kalxas** [comment]
ok, sounds good

**Comment by HamishB** [comment]
(it's now made its way into testing, great work guys!)

**Comment by tomkralidis** [comment]
@johanvdw:

- can we fix the naming as per https://github.com/geopython/pycsw/issues/75#issuecomment-114060612?
- is pycsw now in debian-backports?

**Comment by sebastic** [comment]
pycsw is not in backports.

**Comment by tomkralidis** [comment]
Any update on this one?

**Comment by sebastic** [comment]
Debian stretch was just released, so pycsw is available to Debian stable users.

jessie users should upgrade to stretch.

The case in the description has been fixed, the change will be included in the next upload when the package in experimental is moved to unstable (for migration to testing and inclusion in the next stable release).

**Comment by kalxas** [comment]
I consider this one done.
