### ISSUE TITLE
Resolver error at paths./search.get.parameters.11.$ref

### ISSUE THREAD

**Issue by securedimensions** [geopython/pycsw#755]
# Description
After opening one of the Data operations this error is displayed at the top:
````
Resolver error at paths./collections/{collectionId}/items.get.parameters.11.$ref
Could not resolve reference: Could not resolve pointer: /components/parameters/vendorSpecificParameters does not exist in document
```` 

# Environment
pycsw 3.0 dev
- operating system:
Ubuntu 22
- Python version:
3.10.4
- pycsw version:
git:latest
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [x] other (please specify): Apache2 reverse proxy

# Steps to Reproduce
http://localhost/openapi?f=html#/Data/getRecords

# Additional Information

**Comment by tomkralidis** [comment]
@securedimensions thanks for the report.  This is now fixed in master via #757.
