### ISSUE TITLE
homepage at docker links to non existing /pycsw/csw.py

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#769]
when starting the latest docker (8014385e0352)
the homepage opens fine
but any link to other location throws 404
it is because the links are prepended with /pycsw/csw.py, removing this from the link gives a correct page

eg: http://localhost:8000/pycsw/csw.py/collections -> http://localhost:8000/collections

Is it this configuration causing it? https://github.com/geopython/pycsw/blob/44bfd9532f306e3ba3a8713dd21603bf5be592c4/default-sample.cfg#L32, can the image be prepopulated with a correct path configuration?

**Comment by tomkralidis** [comment]
Thanks for reporting and fixing @pvgenuchten! 💪 🚀
