### ISSUE TITLE
internal server error on demo / items

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#778]
the following url throws an internal server error
https://demo.pycsw.org/gisdata/collections/metadata:main/items

**Comment by tomkralidis** [comment]
Thanks @pvgenuchten.  Fixed via https://github.com/geopython/demo.pycsw.org/commit/396f32cfe997aabf2fee5d870dd4fbec9728a1ed

**Comment by pvgenuchten** [comment]
Thanx tom
