### ISSUE TITLE
Cannot use :memory: as SQLite database

### ISSUE THREAD

**Issue by frafra** [geopython/pycsw#818]
A file path is expected.

https://github.com/geopython/pycsw/blob/d207854c84dfbf391df2d49dfa5df014357783b3/pycsw/core/admin.py#L60

**Comment by tomkralidis** [comment]
@frafra addressed in #825.  Can you validate?

**Comment by frafra** [comment]
Thank you for the patch. The problem is that creating the database and loading the data happens with two different connections, so the first database is lost. That would then require a major change, to both the command line (adding something like `--initdb` when adding the data) and to the internal code, as `setup_db` should return the connection, which should be then reused for other operations.

I am not sure if it is worth the effort. It could be easier just to roll back the change and document that a file is needed :)

**Comment by tomkralidis** [comment]
Thanks for the feedback.  I think we will leave this in the codebase, given that for those using pycsw as a library, one can build their own workflow, which starts up an instance, loads metadata and serves/run (perhaps with a periodic flush to disk workflow).

**Comment by frafra** [comment]
That is my case, actually, but it is not covered by this patch.
pycsw functions do not work in such scenario, as they take the database name instead of the database connection that has being opened already. `setup_db` will always close the connection, thus destroying the database in memory each time.
