### ISSUE TITLE
linkage between records

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#850]
# Description

Does pycsw offer a capability to establish links between records? These links would then be advertised in the link section of an ogc-api-records representation. Common linkages in metadata are the parent-child relation and the service-dataset link. However iso19139 describes a number of alternative linkages for example via the  [aggregationInfo](http://www.datypic.com/sc/niem21/e-gmd_aggregationInfo-1.html) element.

**Comment by pvgenuchten** [comment]
initial research, db model has `parentidentifier` and `relation`, relation is populated from [iso.aggregationinfo](https://github.com/geopython/pycsw/blob/3243c43c613d1fc951f3aacd6c00cbbeba119a6a/pycsw/core/metadata.py#L1406) as [simpleText](https://github.com/geopython/OWSLib/blob/bc88ee1a6509746cff1cccfbad6e6501bae4c256/owslib/iso.py#L406)

Both parentidentifier and relation contain uri's/uuid's to linked records. OGCAPI-records expects URI's. 

Suggestion would be to use item-url as link to record on records links object, unless identifier is already a url (startswith(http))

**Comment by pvgenuchten** [comment]
#880 optimizes the orgapi-records representation of a record, it does not cover other aspects in this issue such as parentidentifier, aggregationinfo etc, suggest to keep issue open, or shall i create targeted issues?

**Comment by tomkralidis** [comment]
Thanks @pvgenuchten; target issues would be great
