### ISSUE TITLE
terriajs assumes filter property 'OnlineResourceType' on csw

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#867]
csw client in terriajs assumes a filter property 'OnlineResourceType'

for that reason the initial csw request fails

is it possible to add this property by configuration and can we provide some guidance to use terriajs with pycsw

**Comment by tomkralidis** [comment]
@pvgenuchten suggest closing given this is not an official queryable, and a workaround has been found.

**Comment by pvgenuchten** [comment]
Yes we can close
