### ISSUE TITLE
Docker build of 2.6 branch will not start

### ISSUE THREAD

**Issue by etj** [geopython/pycsw#891]
# Description

The docker image created on the live 2.6 branch will not run (even once fixed via #890), because of a bad dependency (see https://github.com/geopython/geolinks/issues/13).

When running a `docker run` on the image, you'll get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/entrypoint.py", line 52, in <module>
    from pycsw.core import admin
  File "/home/pycsw/pycsw/pycsw/core/admin.py", line 38, in <module>
    from pycsw.core import metadata, repository, util
  File "/home/pycsw/pycsw/pycsw/core/metadata.py", line 38, in <module>
    from geolinks import sniff_link
  File "/usr/local/lib/python3.8/site-packages/geolinks/__init__.py", line 34, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

# Environment

- operating system:
- pycsw version: branch 2.6 
- source/distribution
  - [x] git clone

# Steps to Reproduce

- Checkout pycsw at branch 2.6
- Apply #890 in order to have a valid Dockerfile
- Build the image
  ```
  docker build . --tag pycsw:2.6.x
  ```
- Run the image
  ```
  docker run -p 8000:8000 pycsw:2.6.x
  ```
# Additional Information

**Comment by tomkralidis** [comment]
FYI geolinks 0.2.2 has just been released.  Let us know if this fixes the issue.

**Comment by etj** [comment]
@tomkralidis fixed, thanks!
