### ISSUE TITLE
yaml scanner error: could not find expected ":" in "/etc/pycsw/pycsw.yml"

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [geopython/pycsw#943]
# Description
I am trying to run docker using a bind mount as described [here](https://docs.pycsw.org/en/latest/docker.html#pycsw-configuration). I receive the following error:

raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key in "/etc/pycsw/pycsw.yml", line 109, column 9
could not find expected ':'in "/etc/pycsw/pycsw.yml", line 110, column 9

# Command
`docker run --name pycsw --detach --volume ./pycsw.yml:/etc/pycsw/pycsw.yml --publish 8000:8000 geopython/pycsw`

# My custom configuration file
[pycsw.zip](https://github.com/geopython/pycsw/files/13976888/pycsw.zip)

# Environment
- operating system: Windows 10 Pro
- pycsw version: latest
- source/distribution
  - [x] git clone

# Steps to Reproduce
Clone the latest version of pycsw and run the docker command above.

**Comment by pvgenuchten** [comment]
hi Kate, i noticed also this behaviour, it relates to the recent change of the [config file](https://github.com/geopython/pycsw/blob/master/default-sample.yml) to use yaml
I solved it by mounting a customised yaml file into the container
but would be good to fix the default docker image
