### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR: -337 on /csw endpoint

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#954]
# Description

When running a request to /csw endpoint of pycsw default docker (with http2 enabled and nginx ingress), the browser (firefox, chrome) throws a ERR_HTTP2_PROTOCOL_ERROR: -337 (chrome) or ns_error_net_partial_transfer (firefox)

I'm not sure what's going on, this error did not occur on a docker image from some months ago

Various reports indicate that it is caused by an unexpected header, such as https://www.rhymewithgravy.com/2016/08/23/Beware-the-Connection-Header-in-HTT-P.html

we found a difference between a running service (some months old) and a new service, the older service does not provide compression of results:

```
  curl 'https://rwanda.lsc-hubs.org/csw' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' -H 'Cookie: _pk_id.325.ff8b=551f7ef89f1c53c4.1688641971.' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'

  curl 'https://kenya.lsc-hubs.org/csw' --compressed -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' -H 'Cookie: _pk_id.323.a6cc=a59ffa75ded899e9.1706871174.' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'TE: trailers'
```

# Environment

- operating system: Windows Chrome/Firefox
- Python version: 3.8
- pycsw version: master
- web server
  - [x] other (please specify): gunicorn (docker), with nginx ingress enabling CORS

# Steps to Reproduce

- deploy docker with nginx ingress
- run fetch('localhost:8000/csw')

**Comment by pvgenuchten** [comment]
I just noticed on docs:

```
gzip_compresslevel: gzip compression level, lowest is 1, highest is 9. Default is off. NOTE: if gzip compression is already enabled via your web server, do not enable this directive (or else the server will try to compress the response twice, resulting in degraded performance)
```

with the new yaml encoded config, this slipped in

**Comment by pvgenuchten** [comment]
@keul, did you disable gzip compress in pycsw config?

**Comment by keul** [comment]
It _is_ activated. If I disable it, the problem disappear, but I don't get why. 
It should not be a problem on its own as I don't have any other gzip compression activated in front of the CSW service.

**Comment by pvgenuchten** [comment]
It is the same issue as mine, suggestion to disable it, compression at python side is unexpected these days

**Comment by keul** [comment]
@pvgenuchten wow, any known reference about this issue with Python?
Because, if this is the problem, I would expect to have an open issue in pycsw opened. Seems a nasty problem.

Also: this does not seems to be fully true on my side.

- if I directly access the pycsw service (with gzip enabled), my browser does not complain, but…
- if I access pycsw through a proxy (proxy that is _not compressing_ again in gzip) I've the issue

What is driving me mad is that proxy is not adding any additional headers, apart SSL compression. So maybe is a matter of SSL+gzip? 🤯

**Comment by keul** [comment]
@pvgenuchten FYI: think I found the root of the problem - https://github.com/geopython/pycsw/pull/1053
